import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { dayLabel, londonToday, mondayOf, validDateKey } from '@/lib/dates';
import { loadWeek, selectedWeek } from '@/lib/week-data';
import { formatGBP, poundsInput } from '@/lib/money';
import { SalesForm } from '@/components/sales-form';
import { WeekNavigation } from '@/components/week-navigation';
export default async function Sales({searchParams}:{searchParams:Promise<{week?:string|string[];date?:string}>}) {
  const user=await requireUser(); const today=londonToday(); const query=await searchParams;
  const date=query.date&&validDateKey(query.date)?query.date:query.week?selectedWeek(query.week,today):today;
  const monday=mondayOf(date); const {week,days}=await loadWeek(user.restaurantId,monday); const selected=days.find(d=>d.date===date); const admin=user.role==='SUPER_USER';
  return <><p className="eyebrow">Daily takings · excluding VAT</p><h1 className="page-title">Daily Sales</h1><WeekNavigation monday={monday} path="/sales" current={mondayOf(today)}/><section className="card mb-5 max-w-xl"><form className="mb-5 flex flex-wrap items-end gap-3"><div className="min-w-0 grow"><label htmlFor="sales-date">Sales date</label><input id="sales-date" name="date" type="date" defaultValue={date} max={today} required/></div><button className="btn btn-secondary">Choose day</button></form><h2 className="section-title">{dayLabel(date)}</h2>{!week?<p>A Super User must <Link href={`/admin/planning?week=${monday}`} className="underline">create this week&apos;s plan</Link> before sales can be entered.</p>:week.finalizedAt?<p>This week is finalized. Ask a Super User to reopen it before correcting sales.</p>:date>today?<p>Future actual sales cannot be entered.</p>:selected?.sale&&!admin?<p>Recorded: {formatGBP(selected.sale.amountPence)}. Ask a Super User to make a correction.</p>:<SalesForm key={`${date}-${selected?.sale?.version??0}`} date={date} version={selected?.sale?.version??0} amount={selected?.sale?poundsInput(selected.sale.amountPence):''} reasonRequired={!!selected?.sale||monday!==mondayOf(today)}/>}</section><section className="card"><h2 className="section-title">This week&apos;s sales</h2><div className="overflow-x-auto"><table className="data-table compact-sales"><thead><tr><th>Day</th><th>Original forecast</th><th>Actual net sales</th><th>Entry</th></tr></thead><tbody>{days.map(d=><tr key={d.date}><td>{dayLabel(d.date).slice(0,3)}</td><td>{d.forecast?formatGBP(d.forecast.originalForecastPence):'—'}</td><td>{d.sale?formatGBP(d.sale.amountPence):'—'}</td><td>{d.date<=today&&<Link className="underline" href={`?date=${d.date}`}>{d.sale?'View':'Enter'}</Link>}</td></tr>)}</tbody></table></div></section></>;
}
