import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { addDays, dateKey, londonToday, mondayOf, dayLabel } from '@/lib/dates';
import { selectedWeek } from '@/lib/week-data';
import { financialWeek } from '@/lib/financial-data';
import { supplierReport } from '@/lib/supplier-report';
import type { SalesDay } from '@/lib/sales';
import { cumulativeSales, reportStatus } from '@/lib/reporting';
import { formatGBP } from '@/lib/money';
import { percentLabel } from '@/lib/targets';
import { ratioBps, ratioLabel } from '@/lib/finance';
import { WeekNavigation } from '@/components/week-navigation';
import { OperationForm } from '@/components/operation-form';
import { ReportChart, PrintReport } from '@/components/report-chart';
import { LiveRefresh } from '@/components/live-refresh';
const currency=(v:bigint|null|undefined)=>v==null?'—':formatGBP(v);
const plot=(v:bigint)=>Number(v)/100; // Visual coordinates only; displayed values and calculations remain exact.
function Summary({rows}:{rows:[string,string][]}){return <dl className="financial-summary mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{rows.map(([label,value])=><div className="card" key={label}><dt className="text-xs text-stone-500">{label}</dt><dd className="mt-2 text-xl font-semibold tabular-nums">{value}</dd></div>)}</dl>;}
function DailyPurchaseChart({days,invoices}:{days:SalesDay[];invoices:{accountingDate:Date;amountPence:bigint}[]}) {
  const rows=days.map(day=>({label:dayLabel(day.date).slice(0,3),sales:plot(day.actualPence??0n),purchases:plot(invoices.filter(i=>dateKey(i.accountingDate)===day.date).reduce((sum,i)=>sum+i.amountPence,0n))}));
  const max=Math.max(1,...rows.flatMap(r=>[r.sales,r.purchases]));
  return <div className="weekly-bars" aria-label="Daily net sales versus food purchases">{rows.map(r=><div className="weekly-bar-day" key={r.label}><div className="weekly-bar-track"><span className="weekly-bar weekly-bar-sales" style={{height:`${Math.max(2,(r.sales/max)*100)}%`}}/><span className="weekly-bar weekly-bar-purchases" style={{height:`${Math.max(2,(r.purchases/max)*100)}%`}}/></div><span>{r.label}</span></div>)}</div>;
}
function ExecutiveWeeklyReport({monday,data,state,supplierData}:{monday:string;data:Awaited<ReturnType<typeof financialWeek>>;state:ReturnType<typeof reportStatus>;supplierData:Awaited<ReturnType<typeof supplierReport>>}) {
  const actualSales=data.sales?.actualPence??0n; const actualBps=ratioBps(data.purchases,actualSales); const targetAmount=actualSales*BigInt(data.target.targetBps)/10000n; const variance=targetAmount-data.purchases; const varianceBps=actualBps===null?null:BigInt(data.target.targetBps)-actualBps;
  const byDay=data.days.map(day=>({day,items:data.invoices.filter(i=>dateKey(i.accountingDate)===day.date)}));
  return <article className="executive-report">
    <header className="executive-report-header"><div><div className="executive-brand">COCOTTE</div><div className="executive-brand-sub">RESTAURANT</div></div><div className="text-right"><h1>Weekly Financial Report</h1><p>{dayLabel(monday)} – {dayLabel(addDays(monday,6))}</p><p>Status: {state.status} · All amounts exclude VAT (net)</p></div></header>
    <section><h2>1. Executive Summary</h2><div className="executive-kpis">
      <div><span>Total Net Sales</span><strong>{currency(actualSales)}</strong></div><div><span>Total Food Purchases</span><strong>{currency(data.purchases)}</strong></div><div><span>Purchasing Target</span><strong>{percentLabel(data.target.targetBps)}</strong><small>Target amount {currency(targetAmount)}</small></div><div><span>Actual Purchasing %</span><strong>{ratioLabel(actualBps)}</strong></div><div className={variance>=0n?'executive-highlight':'executive-highlight executive-over'}><span>{variance>=0n?'Under Purchasing Budget':'Over Purchasing Budget'}</span><strong>{varianceBps===null?'—':`${(Number(varianceBps<0n?-varianceBps:varianceBps)/100).toFixed(1)}%`}</strong><b>{currency(variance>=0n?variance:-variance)}</b></div>
    </div></section>
    <section><h2>2. Daily Net Sales</h2><table className="executive-table"><thead><tr><th>Day</th><th>Date</th><th>Net Sales (£)</th></tr></thead><tbody>{data.days.map(d=><tr key={d.date}><td>{dayLabel(d.date).split(' ')[0]}</td><td>{dayLabel(d.date)}</td><td>{currency(d.actualPence)}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Total</th><th>{currency(actualSales)}</th></tr></tfoot></table></section>
    <section className="executive-page-break"><h2>3. Daily Food Purchases by Supplier</h2><table className="executive-table"><thead><tr><th>Day</th><th>Supplier</th><th>Reference</th><th>Amount (£)</th></tr></thead><tbody>{byDay.flatMap(({day,items})=>items.length?items.map((i,index)=><tr key={i.id}><td>{index===0?dayLabel(day.date):''}</td><td>{i.supplier.name}</td><td>{i.id.slice(0,8)}</td><td>{currency(i.amountPence)}</td></tr>):[<tr key={day.date}><td>{dayLabel(day.date)}</td><td>—</td><td>—</td><td>£0.00</td></tr>])}</tbody><tfoot><tr><th colSpan={3}>Total Food Purchases (Net)</th><th>{currency(data.purchases)}</th></tr></tfoot></table></section>
    <section className="executive-page-break"><h2>4. Daily Net Sales vs Food Purchases</h2><DailyPurchaseChart days={data.days} invoices={data.invoices}/><h2>5. Food Purchases by Supplier</h2><table className="executive-table"><thead><tr><th>Supplier</th><th>Total Spend (£)</th><th>% of Total</th></tr></thead><tbody>{supplierData.totals.map(s=><tr key={s.id}><td>{s.name}</td><td>{currency(s.amount)}</td><td>{ratioLabel(ratioBps(s.amount,supplierData.total))}</td></tr>)}</tbody><tfoot><tr><th>Total</th><th>{currency(supplierData.total)}</th><th>{supplierData.total>0n?'100.00%':'—'}</th></tr></tfoot></table></section>
    <section className="executive-page-break"><h2>6. Purchasing Target vs Actual</h2><table className="executive-table"><thead><tr><th>Item</th><th>Amount (£)</th><th>% of Net Sales</th></tr></thead><tbody><tr><td>Total Net Sales</td><td>{currency(actualSales)}</td><td>100.00%</td></tr><tr><td>Total Food Purchases</td><td>{currency(data.purchases)}</td><td>{ratioLabel(actualBps)}</td></tr><tr><td>Purchasing Target</td><td>{currency(targetAmount)}</td><td>{percentLabel(data.target.targetBps)}</td></tr><tr className="executive-variance"><th>{variance>=0n?'Under budget':'Over budget'}</th><th>{currency(variance>=0n?variance:-variance)}</th><th>{varianceBps===null?'—':`${(Number(varianceBps<0n?-varianceBps:varianceBps)/100).toFixed(1)}%`}</th></tr></tbody></table><div className={variance>=0n?'executive-result':'executive-result executive-result-over'}>{varianceBps===null?'Purchasing percentage unavailable':`Final result: ${(Number(varianceBps<0n?-varianceBps:varianceBps)/100).toFixed(1)}% ${variance>=0n?'under':'over'} target · ${currency(variance>=0n?variance:-variance)} ${variance>=0n?'under':'over'} budget`}</div><h2>7. Key Points</h2><ul className="executive-points"><li>Weekly net sales: {currency(actualSales)}.</li><li>Confirmed food purchases: {currency(data.purchases)} ({ratioLabel(actualBps)} of net sales).</li><li>Purchasing target: {percentLabel(data.target.targetBps)}.</li>{supplierData.totals[0]&&<li>Largest supplier spend: {supplierData.totals[0].name} at {currency(supplierData.totals[0].amount)} ({ratioLabel(ratioBps(supplierData.totals[0].amount,supplierData.total))}).</li>}</ul></section>
  </article>;
}
export default async function Reports({searchParams}:{searchParams:Promise<{week?:string|string[];tab?:string;month?:string;supplier?:string}>}) {
  const user=await requireUser();const today=londonToday();const query=await searchParams;const monday=selectedWeek(query.week,today);
  const tab=['sales','purchasing','suppliers','history'].includes(query.tab??'')?query.tab!:'sales';
  const data=await financialWeek(user.restaurantId,monday,today);
  const state=reportStatus({monday,today,recordedDays:data.sales?.recordedDays??0,opening:data.opening,closing:data.closing,purchasesConfirmed:data.purchasesComplete,outstandingOrders:data.orders.length});
  const cumulative=cumulativeSales(data.days);
  const actualCost=data.purchases;
  const actualBps=ratioBps(actualCost,data.sales?.actualPence??0n);
  const history:Awaited<ReturnType<typeof financialWeek>>[]=[];
  if(tab==='history') for(let i=0;i<12;i++) history.push(await financialWeek(user.restaurantId,addDays(monday,-7*i),today));
  const supplierData=tab==='suppliers'?await supplierReport(user.restaurantId,monday,query.month,query.supplier):null;
  const executiveSupplierData=tab==='purchasing'?await supplierReport(user.restaurantId,monday):null;
  const suppliers=tab==='suppliers'?await db().supplier.findMany({where:{restaurantId:user.restaurantId},orderBy:{name:'asc'}}):[];
  const events=tab==='purchasing'&&data.week?await db().auditLog.findMany({where:{restaurantId:user.restaurantId,entity:'WeeklyForecast',entityId:data.week.id,action:{in:['WEEK_FINALIZED','WEEK_REOPENED']}},include:{actor:{select:{name:true}}},orderBy:{createdAt:'desc'}}):[];
  const exportQuery=new URLSearchParams({week:monday,tab,...(supplierData?.month?{month:supplierData.month}:{}),...(query.supplier?{supplier:query.supplier}:{})});
  const costRows=[{label:'Weekly target',value:data.target.targetBps/100,valueExact:percentLabel(data.target.targetBps)},...(data.finance?.projectedBps==null?[]:[{label:'Projected',value:Number(data.finance.projectedBps)/100,valueExact:ratioLabel(data.finance.projectedBps)}]),...(actualBps===null?[]:[{label:state.status==='Final'?'Final actual':'Provisional actual',value:Number(actualBps)/100,valueExact:ratioLabel(actualBps)}])];
  return <><LiveRefresh/><header className="report-heading mb-5 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Cocotte financial intelligence</p><h1 className="page-title mb-2!">Reports</h1><p className="text-sm text-stone-500">{dayLabel(monday)} – {dayLabel(addDays(monday,6))} · GBP · excluding VAT</p><span className="badge mt-3">{state.status}</span></div><div className="report-actions flex flex-wrap gap-2"><Link className="btn" href={`/reports/export?${exportQuery}`}>Export to CSV</Link><PrintReport/></div></header>
    <div className="report-actions"><WeekNavigation monday={monday} path="/reports" current={mondayOf(today)} query={{tab}}/></div>
    <nav className="report-tabs mb-6 flex flex-wrap gap-2" aria-label="Report sections">{[['sales','SALES'],['purchasing','FOOD PURCHASING'],['suppliers','SUPPLIERS'],['history','WEEKLY HISTORY']].map(([key,label])=><Link key={key} href={`?week=${monday}&tab=${key}`} aria-current={tab===key?'page':undefined} className={`rounded-lg px-4 py-3 text-xs font-semibold ${tab===key?'bg-[#214a37] text-white':'bg-white text-[#214a37]'}`}>{label}</Link>)}</nav>
    {tab==='sales'&&<><Summary rows={[[ 'Original weekly forecast',currency(data.sales?.originalPence)],['Actual sales recorded to date',currency(data.sales?.actualPence)],['Updated projected weekly sales',currency(data.sales?.projectedPence)],['Variance · recorded days',currency(data.sales?.variancePence)]]}/><section className="card"><h2 className="section-title">Cumulative sales performance</h2><p className="mb-4 text-xs text-stone-500">£ net sales · actual points appear only for recorded days, including recorded zero sales.</p><ReportChart kind="sales" rows={cumulative.map(d=>({label:dayLabel(d.date).slice(0,3),forecast:plot(d.cumulativeForecast),forecastExact:currency(d.cumulativeForecast),actual:d.cumulativeActual===null?null:plot(d.cumulativeActual),actualExact:currency(d.cumulativeActual)}))}/><div className="overflow-x-auto"><table className="data-table"><thead><tr>{['Day','Forecast net sales','Actual net sales','Daily variance','Cumulative forecast','Cumulative actual'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{cumulative.map(d=><tr key={d.date}><td>{dayLabel(d.date)}</td><td>{currency(d.originalPence)}</td><td>{currency(d.actualPence)}</td><td>{d.actualPence===null?'—':currency(d.actualPence-d.originalPence)}</td><td>{currency(d.cumulativeForecast)}</td><td>{currency(d.cumulativeActual)}</td></tr>)}</tbody></table></div>{!cumulative.length&&<p className="py-5 text-sm">No forecast exists for the selected week.</p>}</section></>}
    {tab==='purchasing'&&<>{executiveSupplierData&&<ExecutiveWeeklyReport monday={monday} data={data} state={state} supplierData={executiveSupplierData}/>}<div className="screen-report-detail"><Summary rows={[[ 'Weekly available to spend · projected',currency(data.finance?.allowance)],['Maximum purchasing budget',currency(data.finance?.purchasingBudget)],['Food purchases · '+(state.status==='Final'?'final':'provisional'),currency(actualCost)],['Purchasing percentage · '+(state.status==='Final'?'final':'provisional'),ratioLabel(actualBps)]]}/>{state.missing.length>0&&<div className="notice mb-5"><p className="font-semibold">Purchasing percentage is provisional</p><ul className="mt-2 list-disc pl-5 text-sm">{state.missing.map(s=><li key={s}>{s}</li>)}</ul>{(data.sales?.actualPence??0n)===0n&&<p className="mt-2 text-sm">A purchasing percentage requires positive recorded net sales.</p>}</div>}<div className="grid gap-5 xl:grid-cols-2"><section className="card"><h2 className="section-title">Purchasing allowance calculation</h2><dl className="divide-y divide-stone-100 text-sm">{[
      ['Original weekly sales forecast',currency(data.sales?.originalPence)],['Actual sales to date',currency(data.sales?.actualPence)],['Updated projected weekly sales',currency(data.sales?.projectedPence)],['Weekly purchasing target',percentLabel(data.target.targetBps)],['Maximum permitted food purchases',currency(data.finance?.maximum)],['Maximum weekly purchasing budget',currency(data.finance?.purchasingBudget)],['Confirmed purchases',currency(data.purchases)],['Weekly available to spend',currency(data.finance?.allowance)]
    ].map(([label,value])=><div key={label} className="flex justify-between gap-4 py-3"><dt>{label}</dt><dd className="shrink-0 font-medium tabular-nums">{value}</dd></div>)}</dl><p className="mt-5 text-xs leading-6 text-stone-600">Purchasing budget = projected net sales × weekly target.<br/>Available to spend = purchasing budget − confirmed food purchases.<br/>Final purchasing % = confirmed food purchases ÷ total actual net sales × 100. Stock values do not affect purchasing control.</p></section><section className="card"><h2 className="section-title">Food purchasing versus target</h2><ReportChart kind="cost" rows={costRows}/><table className="data-table"><thead><tr><th>Measure</th><th>Percentage</th></tr></thead><tbody>{costRows.map(r=><tr key={r.label}><td>{r.label}</td><td>{r.valueExact}</td></tr>)}</tbody></table><p className="mt-4 text-xs text-stone-500">Projected purchasing % uses confirmed food purchases and projected net sales. Final purchasing % uses confirmed food purchases and all seven days of actual net sales. Stock is tracked separately.</p><p className="mt-4 text-xs">Originally assigned target: {percentLabel(data.target.originalBps)} · Current target: {percentLabel(data.target.targetBps)}</p></section></div>
      {user.role==='SUPER_USER'&&data.week&&<details className="card mt-5 report-actions"><summary className="font-semibold">Week close & audited corrections</summary><div className="mt-5 space-y-5"><Link className="underline" href={`/admin/planning?week=${monday}`}>Edit weekly planning (stock optional)</Link>{data.week.finalizedAt?<OperationForm operation="reopen" hidden={{weekStart:monday,stamp:data.week.updatedAt.toISOString()}} fields={[{name:'reason',label:'Reason to reopen finalized week'}]} button="Reopen week"/>:<><OperationForm operation="finalize" hidden={{weekStart:monday,stamp:data.week.updatedAt.toISOString()}} button="Finalize week"/></>}</div></details>}
      <details className="card mt-5"><summary>Reported snapshots & reopening history</summary>{!events.length&&<p className="mt-4 text-sm">No finalized report snapshots yet.</p>}{events.map(event=>{const snap=event.after as Record<string,string|number|null>;return <article key={event.id} className="border-t py-4 text-sm"><p>{event.action.replaceAll('_',' ')} · {event.actor?.name} · {event.createdAt.toISOString()}</p>{event.action==='WEEK_FINALIZED'&&<p>Reported target {percentLabel(Number(snap.targetBps))} · Sales {currency(BigInt(snap.actualSalesPence??0))} · Food purchases {currency(BigInt(snap.purchasesPence??0))}</p>}<p>{event.reason}</p></article>;})}</details></div></>}
    {tab==='suppliers'&&supplierData&&<><form className="card report-actions mb-5 grid items-end gap-4 sm:grid-cols-3"><input type="hidden" name="week" value={monday}/><input type="hidden" name="tab" value="suppliers"/><div><label htmlFor="report-month">Month (leave blank for selected week)</label><input id="report-month" name="month" type="month" defaultValue={supplierData.month??''}/></div><div><label htmlFor="report-supplier">Supplier</label><select id="report-supplier" name="supplier" defaultValue={query.supplier??''}><option value="">All suppliers</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}{s.active?'':' (inactive)'}</option>)}</select></div><button className="btn">Apply filters</button></form><p className="mb-4 text-sm">Supplier reporting period: {dayLabel(supplierData.start)} – {dayLabel(addDays(supplierData.end,-1))}</p><Summary rows={[[ 'Total confirmed supplier spending',currency(supplierData.total)],['Confirmed purchases',String(supplierData.invoices.filter(i=>!i.creditForId).length)]]}/><section className="card"><h2 className="section-title">Confirmed supplier spending</h2><ReportChart kind="suppliers" rows={supplierData.totals.map(s=>({label:s.name,value:plot(s.amount),valueExact:currency(s.amount)}))}/><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Supplier</th><th>Confirmed spending</th><th>Share of total</th><th>Purchases</th></tr></thead><tbody>{supplierData.totals.map(s=><tr key={s.id}><td><Link className="underline" href={`?${new URLSearchParams({week:monday,tab:'suppliers',supplier:s.id,...(supplierData.month?{month:supplierData.month}:{})})}`}>{s.name}</Link></td><td>{currency(s.amount)}</td><td>{ratioLabel(ratioBps(s.amount,supplierData.total))}</td><td>{s.count}</td></tr>)}</tbody><tfoot><tr><th>Total</th><td>{currency(supplierData.total)}</td><td>{supplierData.total>0n?'100.00%':'—'}</td><td>{supplierData.invoices.filter(i=>!i.creditForId).length}</td></tr></tfoot></table></div><p className="mt-4 text-xs text-stone-500">Confirmed purchases less credits, grouped by permanent supplier identity. Renaming or deactivating a supplier preserves all transactions.</p></section><section className="card mt-5"><h2 className="section-title">Purchase detail</h2><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Delivery date</th><th>Supplier</th><th>Order date</th><th>Confirmed net value</th></tr></thead><tbody>{supplierData.invoices.map(i=><tr key={i.id}><td>{dateKey(i.accountingDate)}</td><td>{i.supplier.name}</td><td>{i.orderDate?dateKey(i.orderDate):i.order?dateKey(i.order.orderDate):'—'}</td><td>{currency(i.amountPence)}</td></tr>)}</tbody></table></div>{supplierData.orders.length>0&&<p className="notice mt-3">{supplierData.orders.length} historical unconfirmed orders remain in the legacy tools. Their estimates are excluded from confirmed spending and the available-to-spend calculation.</p>}</section></>}
    {tab==='history'&&<section className="card"><h2 className="section-title">Weekly history</h2><p className="mb-4 text-xs text-stone-500">Twelve Monday–Sunday weeks ending with the selected week. Use the week selector to review older periods.</p><div className="overflow-x-auto"><table className="data-table"><thead><tr>{['Week starting','Original forecast','Actual sales','Target','Opening stock','Actual closing stock','Confirmed purchases','Final purchasing %','Status'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{history.map((w,i)=>{const date=addDays(monday,-7*i);const st=reportStatus({monday:date,today,recordedDays:w.sales?.recordedDays??0,opening:w.opening,closing:w.closing,purchasesConfirmed:w.purchasesComplete,outstandingOrders:w.orders.length});return <tr key={date}><td><Link className="underline" href={`?week=${date}&tab=purchasing`}>{date}</Link></td><td>{currency(w.sales?.originalPence)}</td><td>{currency(w.sales?.actualPence)}</td><td>{percentLabel(w.target.targetBps)}</td><td>{currency(w.opening)}</td><td>{currency(w.closing)}</td><td>{currency(w.purchases)}</td><td>{st.status==='Final'?ratioLabel(w.finance?.actualBps??null):'—'}</td><td>{st.status==='Final'?'Final':'Provisional'}</td></tr>;})}</tbody></table></div></section>}
  </>;
}
