import Link from 'next/link';
import {SimpleInvoiceReview} from '@/components/simple-invoice-review';
import {notFound} from 'next/navigation';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {dateKey} from '@/lib/dates';
import {keyOf} from '@/lib/packaging/values';
import {formatGBP} from '@/lib/money';
import {PackagingForm} from '@/components/packaging-forms';
export default async function Invoice({params}:{params:Promise<{id:string}>}){const user=await requireUser();const {id}=await params;const row=await db().packagingInvoice.findFirst({where:{id,restaurantId:user.restaurantId},include:{supplier:true,document:{select:{id:true,filename:true}},lines:{include:{product:true},orderBy:{position:'asc'}}}});if(!row)notFound();const suppliers=await db().supplier.findMany({where:{restaurantId:user.restaurantId,active:true,...(user.role==='SUPER_USER'?{}:{packagingWorkspace:true})},orderBy:{name:'asc'}});const extraction=row.extraction as {supplierName?:string;net?:string;printedTotal?:string;orderDate?:string;deliveryDate?:string;orderNumber?:string}|null;const suggested=typeof extraction?.supplierName==='string'?extraction.supplierName:'';const matches=suppliers.filter(s=>s.packagingWorkspace&&keyOf(s.name)===keyOf(suggested));const reviewData=(row.review||{}) as Record<string,unknown>;const simpleSaved=reviewData.simpleReview===true;const reviewOrder=simpleSaved?(row.orderDate?dateKey(row.orderDate):''):extraction?.orderDate||'';const reviewDelivery=simpleSaved?(row.deliveryDate?dateKey(row.deliveryDate):''):extraction?.deliveryDate||'';const selected=row.supplierId||(matches.length===1?matches[0].id:'');const events=await db().auditLog.findMany({where:{restaurantId:user.restaurantId,entity:'Packaging',entityId:id},include:{actor:{select:{name:true}}},orderBy:{createdAt:'desc'}});
 return <><Link className="text-sm underline" href="/packaging/invoices">← Invoices</Link><p className="eyebrow mt-4">Packaging & Chemicals · {row.status}</p><h1 className="page-title">{row.supplier?.name??'Awaiting supplier assignment'} · {row.invoiceNumber??'Invoice review'}</h1><p className="mb-4 text-sm" hidden={row.status==='REVIEW'}>Ordered {(row.orderDate?dateKey(row.orderDate):'Not found')} · Delivered {(row.deliveryDate?dateKey(row.deliveryDate):'Not found')}</p>{row.document&&<a className="btn mb-4" href={`/packaging/invoices/${id}/document`}>Download original invoice</a>}
 {row.status==='REVIEW'?<><p className="notice mb-4">{row.scanNote||'Review the original invoice and enter products manually. This invoice is not counted as spending yet.'}</p>{extraction?.printedTotal&&!extraction.net&&<p className="notice mb-3">Printed total: £{extraction.printedTotal} · tax basis unclear. This is not used as net spending; enter the verified amount excluding VAT below.</p>}<section className="card"><h2 className="section-title">Quick review</h2><SimpleInvoiceReview key={`${id}-${row.version}`} id={id} version={row.version} superUser={user.role==='SUPER_USER'} suppliers={suppliers.map(s=>({id:s.id,name:s.name,packagingWorkspace:s.packagingWorkspace}))} supplierId={selected} suggestedSupplier={suggested} orderDate={reviewOrder} deliveryDate={reviewDelivery} orderNumber={row.orderNumber||extraction?.orderNumber||''} initial={(row.review??{}) as Parameters<typeof SimpleInvoiceReview>[0]['initial']}/></section>{row.document&&<details className="card mt-4"><summary>Retry extraction (replaces unsaved/scanned suggestions)</summary><p className="my-3 text-sm">Save any corrections before retrying. Retrying replaces the editable review suggestions; the original document stays unchanged.</p><PackagingForm operation="scan" hidden={{id}} button="Scan original again"/></details>}</>:<section className="card"><h2 className="section-title">{row.status==='VOIDED'?'Voided invoice · excluded from spending':'Confirmed net spending'} · {formatGBP(row.netPence??0n)}</h2><p className="mb-4 text-sm">VAT: {row.vatPence===null?'Not recorded':formatGBP(row.vatPence)} · Gross: {row.grossPence===null?'Not recorded':formatGBP(row.grossPence)}</p><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Original description</th><th>Standard product</th><th>Category</th><th>Quantity / unit</th><th>Pack</th><th>Unit price ex VAT</th><th>Line net</th></tr></thead><tbody>{row.lines.map(l=><tr key={l.id}><td>{l.originalDescription}</td><td><Link className="underline" href={`/packaging/products/${l.productId}`}>{l.product.name}</Link></td><td>{l.category}</td><td>{l.quantity?.toString()??'Unknown'} {l.unit}</td><td>{l.packSize||'Not recorded'}</td><td>{l.unitPrice?`£${l.unitPrice.toFixed(4)}`:'Unknown'}</td><td>{formatGBP(l.netPence)}</td></tr>)}</tbody></table></div>{user.role==='SUPER_USER'&&row.status==='CONFIRMED'&&<details className="mt-5"><summary>Void this invoice with an audit reason</summary><PackagingForm operation="void" hidden={{id}} fields={[{name:'reason',label:'Reason for voiding'}]} button="Void invoice"/></details>}</section>}
 <details className="card mt-4"><summary>Original extracted text (unverified)</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-xs">{row.extractedText||'No extracted text.'}</pre></details><details className="card mt-4"><summary>Audit history</summary>{events.map(e=><p className="mt-3 text-xs" key={e.id}>{e.action.replaceAll('_',' ')} · {e.actor?.name??'System'} · {e.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London'})} · {e.reason}</p>)}</details></>;
}
