import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {londonToday,dateKey} from '@/lib/dates';
import {formatGBP} from '@/lib/money';
import {PackagingForm} from '@/components/packaging-forms';
import {LiveRefresh} from '@/components/live-refresh';
export default async function Invoices(){const user=await requireUser();const today=londonToday();const suppliers=await db().supplier.findMany({where:{restaurantId:user.restaurantId,active:true,packagingWorkspace:true},orderBy:{name:'asc'}});const invoices=await db().packagingInvoice.findMany({where:{restaurantId:user.restaurantId},include:{supplier:true},orderBy:{createdAt:'desc'},take:100});return <><LiveRefresh/><p className="eyebrow">Packaging & Chemicals</p><h1 className="page-title">Invoices</h1><section className="card mb-5" id="upload"><h2 className="section-title">Upload invoice or enter manually</h2>{!suppliers.length?<p>Add or associate a Packaging & Chemicals supplier using the Super User account first.</p>:<PackagingForm operation="upload" hidden={{submissionKey:randomUUID()}} upload button="Upload & review invoice" fields={[{name:'supplierId',label:'Supplier',type:'select',options:suppliers.map(s=>({value:s.id,label:s.name}))},{name:'orderDate',label:'Order date',type:'date',value:today},{name:'deliveryDate',label:'Received / delivery date',type:'date',value:today}]}/>}</section><section className="card"><h2 className="section-title">Recent invoices</h2><p className="mb-3 text-xs text-stone-500">Only confirmed, non-void invoices enter spending reports. Most recent 100 records shown here; use Reports for historical periods.</p><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Supplier</th><th>Order date</th><th>Delivery</th><th>Invoice</th><th>Net</th><th>Review</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><Link className="underline" href={`/packaging/invoices/${i.id}`}>{i.supplier.name}</Link></td><td>{dateKey(i.orderDate)}</td><td>{dateKey(i.deliveryDate)}</td><td>{i.invoiceNumber??'No number'}</td><td>{i.netPence===null?'—':formatGBP(i.netPence)}</td><td>{i.status==='REVIEW'?'Needs review':i.status==='VOIDED'?'Voided':'Confirmed'}</td></tr>)}</tbody></table></div>{!invoices.length&&<p className="py-4 text-sm">No invoices uploaded yet.</p>}</section></>;}
