import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {dateKey} from '@/lib/dates';
import {formatGBP} from '@/lib/money';
import {InvoiceUpload} from '@/components/invoice-upload';
import {LiveRefresh} from '@/components/live-refresh';
export default async function Invoices(){const user=await requireUser();const invoices=await db().packagingInvoice.findMany({where:{restaurantId:user.restaurantId},include:{supplier:true},orderBy:{createdAt:'desc'},take:100});return <><LiveRefresh/><p className="eyebrow">Packaging & Chemicals</p><h1 className="page-title">Invoices</h1><section className="card mb-5" id="upload"><h2 className="section-title">Upload invoice or enter manually</h2><InvoiceUpload submissionKey={randomUUID()}/></section><section className="card"><h2 className="section-title">Recent invoices</h2><p className="mb-3 text-xs text-stone-500">Only confirmed, non-void invoices enter spending reports. Most recent 100 records shown here; use Reports for historical periods.</p><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Supplier</th><th>Order date</th><th>Delivery</th><th>Invoice</th><th>Net</th><th>Review</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><Link className="underline" href={`/packaging/invoices/${i.id}`}>{i.supplier?.name??'Awaiting supplier assignment'}</Link></td><td>{i.orderDate?dateKey(i.orderDate):'Not found'}</td><td>{i.deliveryDate?dateKey(i.deliveryDate):'Not found'}</td><td>{i.invoiceNumber??'No number'}</td><td>{i.netPence===null?'—':formatGBP(i.netPence)}</td><td>{i.status==='REVIEW'?'Needs review':i.status==='VOIDED'?'Voided':'Confirmed'}</td></tr>)}</tbody></table></div>{!invoices.length&&<p className="py-4 text-sm">No invoices uploaded yet.</p>}</section></>;}
