import Link from 'next/link';
import { BookOpen, Plus, Search } from 'lucide-react';
import { requireUser } from '@/lib/auth';
import { recipeTypes, recipes } from '@/lib/recipes';
import { deleteRecipe, deleteRecipeType, saveRecipeType } from './actions';

export default async function RecipesPage({searchParams}:{searchParams:Promise<{q?:string;type?:string;manage?:string}>}){
 const user=await requireUser(),admin=user.role==='SUPER_USER',p=await searchParams,q=(p.q??'').trim().toLowerCase(),type=p.type??'',manage=admin&&p.manage==='types';
 const types=await recipeTypes(user.restaurantId,admin),all=await recipes(user.restaurantId,admin,type||undefined);
 const shown=all.filter(r=>!q||r.name.toLowerCase().includes(q)||r.typeName.toLowerCase().includes(q)).slice(0,12);
 return <><header className="dashboard-heading"><div><p className="eyebrow">Kitchen recipe bible</p><h1 className="page-title">Recipes</h1></div>{admin&&<div className="flex flex-wrap gap-2"><Link className="btn btn-secondary" href={manage?'/recipes':'/recipes?manage=types'}>{manage?'View recipes':'Recipe types'}</Link><Link className="btn" href="/recipes/edit"><Plus size={16}/>ADD RECIPE</Link></div>}</header>
 {manage?<section className="card"><div className="panel-heading"><h2 className="section-title">Recipe types</h2><p className="page-description">Create, order, hide or remove recipe sections.</p></div><form action={saveRecipeType} className="recipe-type-add"><input name="name" required maxLength={100} placeholder="New recipe type"/><input name="sortOrder" type="number" defaultValue={types.length+1} aria-label="Sort order"/><label className="recipe-check"><input name="visible" type="checkbox" defaultChecked/> Visible</label><button className="btn">ADD TYPE</button></form><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Name</th><th>Recipes</th><th>Order</th><th>Visible</th><th>Actions</th></tr></thead><tbody>{types.map(t=><tr key={t.id}><td><form action={saveRecipeType} className="recipe-type-row"><input type="hidden" name="id" value={t.id}/><input name="name" defaultValue={t.name}/><input name="sortOrder" type="number" defaultValue={t.sortOrder}/><label className="recipe-check"><input name="visible" type="checkbox" defaultChecked={t.visible}/> Show</label><button className="btn btn-secondary">SAVE</button></form></td><td>{t.recipeCount}</td><td>{t.sortOrder}</td><td>{t.visible?'Yes':'Hidden'}</td><td><form action={deleteRecipeType}><input type="hidden" name="id" value={t.id}/><button className="text-xs underline">Delete</button></form></td></tr>)}</tbody></table></div></section>:
 <><form className="recipe-filters"><label className="recipe-search"><Search size={16}/><input name="q" defaultValue={p.q} placeholder="Search recipes..." aria-label="Search recipes"/></label><select name="type" defaultValue={type} aria-label="Recipe type"><option value="">All recipe types</option>{types.filter(t=>admin||t.visible).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="btn btn-secondary">FILTER</button></form>
 <section className="recipe-grid">{shown.map(r=><article className="recipe-card" key={r.id}><Link href={'/recipes/'+r.id} className="recipe-card-image">{r.hasImage?<img src={'/recipes/'+r.id+'/image'} alt=""/>:<span><BookOpen size={24}/></span>}</Link><div className="recipe-card-body"><Link href={'/recipes/'+r.id} className="recipe-card-name">{r.name}</Link><p>{r.typeName}{!r.visible&&' · Hidden'}</p>{admin&&<div className="recipe-card-admin"><Link href={'/recipes/edit?id='+r.id}>Edit</Link><form action={deleteRecipe}><input type="hidden" name="id" value={r.id}/><button>Delete</button></form></div>}</div></article>)}</section>{!shown.length&&<div className="card"><p className="text-sm text-stone-500">No recipes match this filter.</p></div>}</>}
 </>;
}
