import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { recipe } from '@/lib/recipes';
export default async function RecipePage({params}:{params:Promise<{id:string}>}){
 const user=await requireUser(),{id}=await params,r=await recipe(user.restaurantId,id,user.role==='SUPER_USER');if(!r)notFound();
 const steps=r.onOrder.split('\n').map(x=>x.trim()).filter(Boolean),prep=r.beforeService.split('\n').map(x=>x.trim()).filter(Boolean);
 return <><header className="recipe-detail-heading"><div><Link href="/recipes" className="text-xs underline">← Back to recipes</Link><p className="eyebrow mt-3">{r.typeName}</p><h1 className="page-title">{r.name}</h1></div>{user.role==='SUPER_USER'&&<Link className="btn btn-secondary" href={'/recipes/edit?id='+r.id}>EDIT RECIPE</Link>}</header>
 <div className="recipe-detail-grid"><div><div className="recipe-hero">{r.hasImage?<img src={'/recipes/'+r.id+'/image'} alt={r.name}/>:<div>No image</div>}</div><div className="recipe-notes"><section className="card"><h2 className="section-title">Allergens</h2><p>{r.allergens||'—'}</p></section><section className="card"><h2 className="section-title">May contain</h2><p>{r.mayContain||'—'}</p></section><section className="card"><h2 className="section-title">Suitability</h2><p>{r.suitability||'—'}</p></section></div></div>
 <div className="space-y-4"><section className="card"><h2 className="section-title">Ingredients</h2><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Ingredient</th><th>Quantity</th><th>Unit</th></tr></thead><tbody>{r.ingredients.map((i,n)=><tr key={n}><td>{i.name}</td><td>{i.quantity}</td><td>{i.unit}</td></tr>)}</tbody></table></div></section><div className="recipe-methods"><section className="card"><h2 className="section-title">Before Service</h2>{prep.map((x,n)=><p className="recipe-step" key={n}>{x}</p>)}</section><section className="card"><h2 className="section-title">On Order</h2>{steps.map((x,n)=><p className="recipe-step" key={n}><strong>{n+1}.</strong> {x}</p>)}</section></div></div></div></>;
}