import {describe,it,expect} from 'vitest';
import {parseInvoiceText} from '../src/lib/packaging/parse';
import {validateDocument,MAX_DOCUMENT_BYTES} from '../src/lib/packaging/document';
import {reviewSchema,reconcile,invoiceNumberKey} from '../src/lib/packaging/values';
import {reportFilters,summarize,type SpendingLine} from '../src/lib/packaging/reporting';
const line:SpendingLine={id:'l1',productId:'soap5',productName:'Washing liquid 5L',category:'CHEMICAL',unit:'bottle',packSize:'5l',quantity:'2',unitPrice:'8',netPence:1600n,invoiceId:'a',invoiceNumber:'A',orderDate:'2026-09-21',deliveryDate:'2026-09-21',supplierId:'s',supplierName:'Supplier',position:0,createdAt:'2026-09-21T12:00:00Z',originalDescription:'W/UP LIQ'};
describe('non-food invoice extraction and accounting',()=>{
 it('keeps an unlabeled invoice total separate from verified net amounts',()=>{const v=parseInvoiceText('Total: £120.00');expect(v.printedTotal).toBe('120.00');expect(v.net).toBe('');expect(v.gross).toBe('');});
 it('extracts explicit net / VAT / gross separately without guessing categories or packs',()=>{const v=parseInvoiceText('Supplier: Acme\nInvoice No: INV-123\nInvoice Date: 21/09/2026\nDescription Qty Unit Price ex VAT Line Total\nWashing Up Liquid 2 bottle 8.00 16.00\nNet total: £16.00\nVAT: £3.20\nGross total: £19.20');expect(v.net).toBe('16.00');expect(v.vat).toBe('3.20');expect(v.gross).toBe('19.20');expect(v.invoiceNumber).toBe('INV-123');expect(v.invoiceDate).toBe('2026-09-21');expect(v.lines[0]).toMatchObject({quantity:'2',unitPrice:'8.00',lineNet:'16.00',packSize:'',uncertain:true});});
 it('never treats gross or an unclear line tax basis as net',()=>{const v=parseInvoiceText('Washing liquid 2 bottle 8.00 16.00\nGross total: 19.20');expect(v.net).toBe('');expect(v.lines[0].lineNet).toBe('');expect(v.lines[0].unitPrice).toBe('');expect(v.warnings.length).toBeGreaterThan(1);});
 it('validates actual file signatures, size and unsupported types',()=>{expect(validateDocument(Buffer.from('%PDF-1.7\n'),'invoice.pdf','application/pdf').mime).toBe('application/pdf');expect(()=>validateDocument(Buffer.from('<script>'),'invoice.pdf','application/pdf')).toThrow();expect(()=>validateDocument(Buffer.from('%PDF-1.7'),'invoice.jpg','image/jpeg')).toThrow();expect(()=>validateDocument(new Uint8Array(MAX_DOCUMENT_BYTES+1),'x.png','image/png')).toThrow();expect(()=>validateDocument(Buffer.from('heic'),'x.heic','image/heic')).toThrow();});
 it('reconciles net pence exactly and flags price and VAT discrepancies',()=>{const v=reviewSchema.parse({invoiceNumber:'A',invoiceDate:'',net:'16',vat:'3.20',gross:'19.20',lines:[{description:'soap',category:'CHEMICAL',unit:'bottle',packSize:'5l',quantity:'2',unitPrice:'8',lineNet:'16'}],netConfirmed:true,reconciled:false});expect(reconcile(v)).toMatchObject({sum:1600n,balanced:true,issues:[]});expect(reconcile({...v,net:'17'}).balanced).toBe(false);expect(reconcile({...v,gross:'20'}).issues).toHaveLength(1);expect(invoiceNumberKey(' inv 001 ')).toBe('INV001');});
 it('counts distinct invoices and order dates while summing repeated lines',()=>{const report=summarize([line,{...line,id:'l2',position:1,quantity:'1',netPence:800n},{...line,id:'l3',invoiceId:'b',orderDate:'2026-09-25',quantity:'2',unitPrice:'8.5',netPence:1700n}]);const p=report.products[0];expect(report.total).toBe(4100n);expect(report.invoiceCount).toBe(2);expect(p.invoiceCount).toBe(2);expect(p.orderDates).toBe(2);expect(p.quantity).toBe(50000n);expect(p.average).toBe(82000n);expect(p.latest).toBe(85000n);expect(p.change).toBe(5000n);});
 it('suppresses aggregates of unknown / unlike units rather than inventing quantities',()=>{expect(summarize([line,{...line,unit:'case'}]).products[0].quantity).toBeNull();expect(summarize([{...line,quantity:null}]).products[0].average).toBeNull();expect(summarize([{...line,unit:''}]).products[0].latest).toBeNull();});
 it('uses Monday–Sunday and real calendar months, validates custom dates',()=>{expect(reportFilters({week:'2026-09-27'})).toMatchObject({start:'2026-09-21',end:'2026-09-27'});expect(reportFilters({period:'month',month:'2028-02'})).toMatchObject({start:'2028-02-01',end:'2028-02-29'});expect(()=>reportFilters({period:'custom',start:'2026-09-30',end:'2026-09-01'})).toThrow();expect(()=>reportFilters({period:'month',month:'2026-13'})).toThrow();});
});
