import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {addDays,dateKey,dateValue,londonToday,mondayOf} from '@/lib/dates';
import {selectedWeek} from '@/lib/week-data';
import {formatGBP,poundsInput} from '@/lib/money';
import {PurchaseForm} from '@/components/purchase-form';
import {OperationForm} from '@/components/operation-form';
import {LiveRefresh} from '@/components/live-refresh';
import {WeekNavigation} from '@/components/week-navigation';
export default async function Purchases({searchParams}:{searchParams:Promise<{week?:string|string[];page?:string}>}) {
  const user=await requireUser();const admin=user.role==='SUPER_USER';const today=londonToday();const query=await searchParams;const monday=selectedWeek(query.week,today);
  const page=query.page&&/^\d{1,5}$/.test(query.page)?Math.max(0,Number(query.page)):0;
  const suppliers=await db().supplier.findMany({where:{restaurantId:user.restaurantId},orderBy:{name:'asc'}});
  const purchases=await db().purchaseInvoice.findMany({where:{restaurantId:user.restaurantId,accountingDate:{gte:dateValue(monday),lte:dateValue(addDays(monday,6))},confirmedAt:{not:null}},include:{supplier:true,order:true},orderBy:[{createdAt:'desc'},{id:'desc'}],take:21,skip:page*20});
  const ids=purchases.slice(0,20).map(p=>p.id);
  const history=admin&&ids.length?await db().auditLog.findMany({where:{restaurantId:user.restaurantId,entity:'PurchaseInvoice',entityId:{in:ids}},include:{actor:{select:{name:true}}},orderBy:{createdAt:'desc'}}):[];
  return <><LiveRefresh/><p className="eyebrow">Cocotte purchasing · net of VAT</p><h1 className="page-title">Supplier Purchases</h1>
    <section className="card mb-5"><h2 className="section-title">Record Supplier Purchase</h2><PurchaseForm suppliers={suppliers.filter(s=>s.active&&s.foodWorkspace).map(({id,name})=>({id,name}))} today={today} submissionKey={randomUUID()}/></section>
    <WeekNavigation monday={monday} path="/orders" current={mondayOf(today)}/>
    <section className="card"><h2 className="section-title">Recent purchases · delivery week</h2><div className="overflow-x-auto" tabIndex={0} role="region" aria-label="Recent purchases"><table className="data-table"><thead><tr><th>Supplier</th><th>Order date</th><th>Delivery date</th><th>Net amount</th><th>Record</th>{admin&&<th>Actions</th>}</tr></thead><tbody>{purchases.slice(0,20).map(p=><tr key={p.id}><td>{p.supplier.name}</td><td>{p.orderDate?dateKey(p.orderDate):p.order?dateKey(p.order.orderDate):'—'}</td><td>{dateKey(p.accountingDate)}</td><td className="font-semibold">{formatGBP(p.amountPence)}</td><td>{p.voidedAt?'Voided':p.creditForId?'Credit':'Confirmed'}</td>{admin&&<td><a className="underline" href={`#purchase-${p.id}`}>Review / correct</a></td>}</tr>)}</tbody></table></div>{!purchases.length&&<p className="py-4 text-sm text-stone-500">No purchases for this delivery week.</p>}<nav className="mt-3 flex gap-4 text-sm" aria-label="Purchase pages">{page>0&&<Link href={`?week=${monday}&page=${page-1}`}>Newer purchases</Link>}{purchases.length>20&&<Link href={`?week=${monday}&page=${page+1}`}>Older purchases</Link>}</nav></section>
    {admin&&purchases.slice(0,20).map(p=><details id={`purchase-${p.id}`} key={p.id} className="card mt-3 purchase-review"><summary>{p.supplier.name} · {dateKey(p.accountingDate)} · {formatGBP(p.amountPence)} · Corrections & audit</summary><div className="mt-4 grid gap-5 lg:grid-cols-2">{!p.voidedAt&&<><OperationForm operation="purchase-correct" hidden={{id:p.id,stamp:p.updatedAt.toISOString()}} fields={[{name:'supplierId',label:'Supplier name',type:'select',value:p.supplierId,options:suppliers.filter(s=>s.active&&s.foodWorkspace||s.id===p.supplierId).map(s=>({value:s.id,label:s.name}))},{name:'orderDate',label:'Order date',type:'date',value:p.orderDate?dateKey(p.orderDate):p.order?dateKey(p.order.orderDate):''},{name:'deliveryDate',label:'Delivery date',type:'date',value:dateKey(p.accountingDate)},{name:'amount',label:'Corrected total EXCLUDING VAT (£)',value:poundsInput(p.amountPence<0n?-p.amountPence:p.amountPence)},{name:'reason',label:'Reason for correction'}]} button="Save correction"/><OperationForm operation="purchase-void" hidden={{id:p.id,stamp:p.updatedAt.toISOString()}} fields={[{name:'reason',label:'Reason to void purchase'}]} button="Void purchase"/></>}<section className="lg:col-span-2"><h3 className="mb-2 font-semibold text-sm">Audit history</h3>{history.filter(e=>e.entityId===p.id).map(e=>{const before=e.before as {amountPence?:string;accountingDate?:string;voidedAt?:string}|null;const after=e.after as {amountPence?:string;accountingDate?:string;voidedAt?:string}|null;return <article className="border-t py-2 text-xs" key={e.id}><p>{e.action.replaceAll('_',' ')} · {e.actor?.name??'System'} · {e.createdAt.toLocaleString('en-GB',{timeZone:'Europe/London'})}</p><p>{before?.amountPence!==undefined?formatGBP(BigInt(before.amountPence)):'—'} → {after?.amountPence!==undefined?formatGBP(BigInt(after.amountPence)):'—'}{after?.voidedAt?' · Voided':''}</p><p>Delivery: {before?.accountingDate?.slice(0,10)??'—'} → {after?.accountingDate?.slice(0,10)??'—'}</p><p>{e.reason}</p></article>;})}</section></div></details>)}
    {admin&&<details className="mt-5 text-xs text-stone-500"><summary>Historical tools</summary><Link className="underline" href={`/admin/legacy-orders?week=${monday}`}>Previous order, invoice and credit-note tools</Link></details>}
  </>;
}
