import Link from 'next/link';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {dateKey,dateValue} from '@/lib/dates';
import {formatGBP} from '@/lib/money';
import {reportFilters} from '@/lib/packaging/reporting';
import {packagingReport} from '@/lib/packaging/data';
import {PackagingFilters,PackagingSummary} from '@/components/packaging-report';
import {LiveRefresh} from '@/components/live-refresh';
export default async function PackagingDashboard({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser();const query=await searchParams;let filters;try{filters=reportFilters(query);}catch(e){return <div className="card"><p role="alert">{(e as Error).message}</p><Link href="/packaging" className="underline">Reset filters</Link></div>;}
 const report=await packagingReport(user.restaurantId,filters);const recent=await db().packagingInvoice.findMany({where:{restaurantId:user.restaurantId,deliveryDate:filters.period==='undated'?null:{gte:dateValue(filters.start),lte:dateValue(filters.end)},...(filters.supplier?{supplierId:filters.supplier}:{}),...((filters.category||filters.product)?{lines:{some:{...(filters.category?{category:filters.category as 'PACKAGING'|'CHEMICAL'|'UNCLASSIFIED'}:{}),...(filters.product?{productId:filters.product}:{})}}}:{})},include:{supplier:true},orderBy:{createdAt:'desc'},take:10});
 const qs=new URLSearchParams({...filters,week:filters.start,month:filters.start.slice(0,7)}).toString();
 return <><LiveRefresh/><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Cocotte · Separate workspace</p><h1 className="page-title">Packaging & Chemicals</h1><p className="text-sm text-stone-500">{filters.period==='undated'?'Undated invoices':`${filters.start} – ${filters.end}`} · Confirmed net spending</p></div><Link href="/packaging/invoices#upload" className="btn btn-primary">UPLOAD INVOICE</Link></header><PackagingFilters restaurantId={user.restaurantId} filters={filters}/><PackagingSummary report={report}/><p className="my-3 text-xs text-stone-500">Reviewed and confirmed invoices only. This spending never reduces the food purchasing allowance.</p><div className="grid gap-4 lg:grid-cols-2">{[['Most frequently purchased', [...report.products].sort((a,b)=>b.invoiceCount-a.invoiceCount).slice(0,5)],['Highest product spending',report.products.slice(0,5)]].map(([title,rows])=><section className="card" key={title as string}><h2 className="section-title">{title as string}</h2><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Product</th><th>Invoices</th><th>Order dates</th><th>Net spending</th></tr></thead><tbody>{(rows as typeof report.products).map(p=><tr key={p.id}><td><Link className="underline" href={`/packaging/products/${p.id}?${qs}`}>{p.name}</Link></td><td>{p.invoiceCount}</td><td>{p.orderDates}</td><td>{formatGBP(p.net)}</td></tr>)}</tbody></table></div>{!(rows as typeof report.products).length&&<p className="py-3 text-sm text-stone-500">No confirmed purchases for this period.</p>}</section>)}</div><section className="card mt-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="section-title">Recent invoices</h2><Link href={`/packaging/reports?${qs}`} className="text-sm underline">View detailed reports</Link></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Supplier / invoice</th><th>Delivered</th><th>Status</th><th>Confirmed net</th></tr></thead><tbody>{recent.map(i=><tr key={i.id}><td><Link className="underline" href={`/packaging/invoices/${i.id}`}>{i.supplier?.name??'Awaiting supplier assignment'} · {i.invoiceNumber||'No number'}</Link></td><td>{i.deliveryDate?dateKey(i.deliveryDate):'Not found'}</td><td>{i.status==='REVIEW'?'Needs review':i.status==='VOIDED'?'Voided':'Confirmed'}</td><td>{i.status==='CONFIRMED'&&i.netPence!==null?formatGBP(i.netPence):'—'}</td></tr>)}</tbody></table></div>{!recent.length&&<p className="py-3 text-sm">Upload an invoice or enter products manually to get started.</p>}</section></>;
}
