'use client';
import {useActionState,useId,useState} from 'react';
import {packagingAction} from '@/app/(protected)/packaging/actions';
import type {Field} from './operation-form';
import type {ReviewLine} from '@/lib/packaging/values';
export function PackagingForm({operation,fields=[],hidden={},button='Save',upload=false}:{operation:string;fields?:Field[];hidden?:Record<string,string>;button?:string;upload?:boolean}){
 const id=useId();const [state,action,pending]=useActionState(packagingAction,{error:'',success:''});
 return <form action={action} className="space-y-3"><input type="hidden" name="operation" value={operation}/>{Object.entries(hidden).map(([k,v])=><input type="hidden" key={k} name={k} value={v}/>)}<div className="grid gap-3 sm:grid-cols-2">{fields.map(f=><div key={f.name}><label htmlFor={`${id}-${f.name}`}>{f.label}</label>{f.type==='select'?<select id={`${id}-${f.name}`} name={f.name} required={f.required!==false} defaultValue={f.value??''}><option value="" disabled>Select…</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input id={`${id}-${f.name}`} name={f.name} type={f.type??'text'} defaultValue={f.value??''} required={f.required!==false} maxLength={500}/>}</div>)}{upload&&<div className="sm:col-span-2"><label htmlFor={`${id}-file`}>Invoice file (optional for manual entry)</label><input id={`${id}-file`} name="file" type="file" accept="application/pdf,image/jpeg,image/png"/><p className="mt-2 text-xs text-stone-500">PDF/JPG/PNG, maximum 8 MB and 5 PDF pages. On your phone, choose Take Photo or Photo Library. Convert HEIC to JPG first. Leave blank to enter products manually.</p></div>}</div>{state.error&&<p role="alert" className="notice">{state.error}</p>}{state.success&&<p role="status" className="text-sm text-green-800">{state.success}</p>}<button className="btn" disabled={pending}>{pending?upload?'Uploading & scanning…':'Saving…':button}</button></form>;
}
type EditableLine=Omit<ReviewLine,'category'>&{category:string};
type ReviewInput={invoiceNumber?:string;invoiceDate?:string;net?:string;vat?:string;gross?:string;lines?:EditableLine[];reason?:string};
const blank=():EditableLine=>({description:'',productId:'',category:'',unit:'',packSize:'',quantity:'',unitPrice:'',lineNet:''});
export function InvoiceReview({id,version,initial,products}:{id:string;version:number;initial:ReviewInput;products:{id:string;name:string;category:string;unit:string;packSize:string}[]}){
 const [values,setValues]=useState({invoiceNumber:initial.invoiceNumber??'',invoiceDate:initial.invoiceDate??'',net:initial.net??'',vat:initial.vat??'',gross:initial.gross??'',reason:initial.reason??'',lines:initial.lines?.length?initial.lines:[blank()],netConfirmed:false,reconciled:false,duplicateReviewed:false});
 const [state,action,pending]=useActionState(packagingAction,{error:'',success:''});
 const update=(i:number,key:string,value:string)=>setValues(v=>({...v,lines:v.lines.map((line,n)=>n===i?{...line,[key]:value}:line)}));
 const exact=(s:string)=>/^\d+(\.\d{1,2})?$/.test(s)?BigInt(s.split('.')[0])*100n+BigInt((s.split('.')[1]??'').padEnd(2,'0')):null;
 const total=values.lines.every(l=>exact(l.lineNet)!==null)?values.lines.reduce((s,l)=>s+exact(l.lineNet)!,0n):null;const net=exact(values.net);
 return <form action={action} className="space-y-4"><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><input type="hidden" name="review" value={JSON.stringify(values)}/>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{([['invoiceNumber','Invoice number'],['invoiceDate','Invoice date'],['net','Invoice net total (£)'],['vat','VAT amount (£), if known'],['gross','Gross total (£), if known']] as const).map(([key,label])=><label key={key}>{label}<input type={key==='invoiceDate'?'date':'text'} value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})} inputMode={['net','vat','gross'].includes(key)?'decimal':undefined}/></label>)}</div>
 <p className="notice">Every scan needs review. Yellow/missing fields are not confirmed values. Prices and line totals must exclude VAT. Leave unknown quantity or unit price blank; never invent them.</p>
 <div className="overflow-x-auto" role="region" aria-label="Editable invoice product lines" tabIndex={0}><table className="data-table review-table"><thead><tr>{['Original description','Standard product','Category','Quantity','Unit','Pack size','Unit price ex VAT (£)','Line net (£)','Actions'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{values.lines.map((line,i)=><tr key={i}><td><input aria-label={`Description ${i+1}`} value={line.description} onChange={e=>update(i,'description',e.target.value)}/></td><td><select aria-label={`Product ${i+1}`} value={line.productId} onChange={e=>{const p=products.find(p=>p.id===e.target.value);setValues(v=>({...v,lines:v.lines.map((l,n)=>n===i?{...l,productId:e.target.value,...(p?{category:p.category,unit:l.unit||p.unit,packSize:l.packSize||p.packSize}:{})}:l)}));}}><option value="">New / unmatched description</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit||'?'} · {p.packSize||'no pack specified'}</option>)}</select></td><td><select aria-label={`Category ${i+1}`} className={!line.category?'review-missing':''} value={line.category} onChange={e=>update(i,'category',e.target.value)}><option value="">Choose…</option><option value="PACKAGING">Packaging</option><option value="CHEMICAL">Chemical</option></select></td>{(['quantity','unit','packSize','unitPrice','lineNet'] as const).map(key=><td key={key}><input aria-label={`${key} ${i+1}`} className={!line[key]?'review-missing':''} value={line[key]} inputMode={['quantity','unitPrice','lineNet'].includes(key)?'decimal':undefined} onChange={e=>update(i,key,e.target.value)}/></td>)}<td><button type="button" className="btn btn-secondary" onClick={()=>setValues({...values,lines:values.lines.filter((_,n)=>n!==i)})}>Remove</button></td></tr>)}</tbody></table></div>
 <button className="btn btn-secondary" type="button" disabled={values.lines.length>=150} onClick={()=>setValues({...values,lines:[...values.lines,blank()]})}>Add product line</button>
 <p className={total!==null&&net!==null&&total===net?'text-sm text-green-800':'notice'}>{total===null||net===null?'Enter all line net totals and the invoice net total to reconcile.':total===net?'Product lines reconcile with the invoice net total.':'Warning: product lines do not match the invoice net total. Correct them before confirmation.'}</p>
 <label>Review explanation (required for discrepancies or possible duplicates)<input value={values.reason} onChange={e=>setValues({...values,reason:e.target.value})}/></label>
 {([['netConfirmed','I checked the original and confirm all line amounts and the invoice net total EXCLUDE VAT.'],['reconciled','I reviewed quantity × price / VAT discrepancies and explained them above.'],['duplicateReviewed','I checked any possible duplicate warning and confirm this is a separate invoice.']] as const).map(([key,label])=><label className="review-confirmation" key={key}><input type="checkbox" checked={values[key]} onChange={e=>setValues({...values,[key]:e.target.checked})}/>{label}</label>)}
 {state.error&&<p role="alert" className="notice">{state.error}</p>}{state.success&&<p role="status">{state.success}</p>}<div className="flex flex-wrap gap-3"><button className="btn btn-secondary" name="operation" value="review" disabled={pending}>Save unconfirmed review</button><button className="btn" name="operation" value="confirm" disabled={pending}>{pending?'Saving…':'Confirm reviewed invoice'}</button></div>
 </form>;
}
