import Link from 'next/link';
import {PackagingFilterForm} from './packaging-filters';
import {db} from '@/lib/db';
import {formatGBP} from '@/lib/money';
import {decimalLabel} from '@/lib/packaging/values';
import {unitPriceLabel,type Filters,summarize} from '@/lib/packaging/reporting';
import {PackagingChart} from './packaging-charts';
export async function PackagingFilters({restaurantId,filters,productId}:{restaurantId:string;filters:Filters;productId?:string}){
 const [suppliers,products]=await Promise.all([db().supplier.findMany({where:{restaurantId,OR:[{packagingWorkspace:true},{packagingInvoices:{some:{}}}]},orderBy:{name:'asc'}}),db().packagingProduct.findMany({where:{restaurantId},orderBy:{name:'asc'}})]);
 return <PackagingFilterForm filters={filters} productId={productId} suppliers={suppliers.map(s=>({id:s.id,name:s.name,active:s.active}))} products={products.map(p=>({id:p.id,name:p.name,unit:p.unit,packSize:p.packSize}))}/>;
}
export function PackagingSummary({report}:{report:ReturnType<typeof summarize>}){return <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Total confirmed spending',formatGBP(report.total)],['Packaging',formatGBP(report.packaging)],['Chemicals',formatGBP(report.chemical)],['Confirmed invoices',String(report.invoiceCount)]].map(([label,value])=><section className="card" key={label}><p className="text-xs text-stone-500">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums sm:text-2xl">{value}</p></section>)}</div>;}
export function ProductSpending({report,query}:{report:ReturnType<typeof summarize>;query:string}){return <section className="card"><h2 className="section-title">Spending by product</h2><p className="text-xs text-stone-500">Top 15 in chart; all products in the table. Purchase frequency measures invoices and order dates, not consumption.</p><PackagingChart rows={report.products.slice(0,15).map(p=>({label:p.name,value:Number(p.net)/100,exact:formatGBP(p.net)}))} label="Net product spending"/><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Product</th><th>Invoices</th><th>Order dates</th><th>Quantity</th><th>Net spending</th><th>Average unit price</th><th>Latest unit price</th><th>Price change</th><th>Suppliers</th></tr></thead><tbody>{report.products.map(p=><tr key={p.id}><td><Link className="underline" href={`/packaging/products/${p.id}?${query}`}>{p.name}</Link><p className="text-xs text-stone-500">{p.category==='CHEMICAL'?'Chemical':'Packaging'} · {p.unit||'Unknown unit'} · {p.packSize||'Pack not recorded'}</p></td><td>{p.invoiceCount}</td><td>{p.orderDates}</td><td>{p.quantity===null?'Not comparable':`${decimalLabel(p.quantity)} ${p.unit}`}</td><td>{formatGBP(p.net)}</td><td>{unitPriceLabel(p.average)}</td><td>{unitPriceLabel(p.latest)}</td><td>{p.change!==null&&p.change>0n?'+':''}{unitPriceLabel(p.change)}</td><td>{p.suppliers.join(', ')}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-stone-500">Average = net line spending ÷ comparable quantity. Unit prices use up to four decimals. Missing quantities or units suppress comparisons; price change compares the earliest and latest recorded prices within this period.</p></section>;}
export function SupplierSpending({report}:{report:ReturnType<typeof summarize>}){return <section className="card"><h2 className="section-title">Spending by supplier</h2><PackagingChart rows={report.suppliers.map(s=>({label:s.name,value:Number(s.net)/100,exact:formatGBP(s.net)}))} label="Confirmed net spending"/><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Supplier</th><th>Confirmed invoices</th><th>Net spending</th><th>Share</th></tr></thead><tbody>{report.suppliers.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.invoiceCount}</td><td>{formatGBP(s.net)}</td><td>{report.total?decimalLabel((s.net*10000n+report.total/2n)/report.total,2)+'%':'—'}</td></tr>)}</tbody><tfoot><tr><th>Total</th><td>{report.invoiceCount}</td><td>{formatGBP(report.total)}</td><td/></tr></tfoot></table></div></section>;}
