'use client';
import {useActionState,useState} from 'react';
import {packagingAction} from '@/app/(protected)/packaging/actions';
import {formatGBP,parsePounds} from '@/lib/money';
type Line={description:string;quantity:string;lineNet:string;category?:string;unit?:string;packSize?:string;printedLineTotal?:string;sourceIndex?:number};
type Initial={invoiceNumber?:string;invoiceDate?:string;vat?:string;gross?:string;net?:string;reason?:string;lines?:Line[]};
export function SimpleInvoiceReview({id,version,initial,suppliers,superUser,supplierId,suggestedSupplier,orderDate,deliveryDate,orderNumber}:{id:string;version:number;initial:Initial;suppliers:{id:string;name:string;packagingWorkspace:boolean}[];superUser:boolean;supplierId:string;suggestedSupplier:string;orderDate:string;deliveryDate:string;orderNumber:string}){
 const [v,set]=useState({supplierId,supplierMode:'select',newSupplierName:suggestedSupplier,orderDate,deliveryDate,orderNumber,invoiceNumber:initial.invoiceNumber||'',invoiceDate:initial.invoiceDate||'',vat:initial.vat||'',gross:initial.gross||'',net:initial.net||'',reason:initial.reason||'',reconciled:false,duplicateReviewed:false,lines:initial.lines?.length?initial.lines.map((l,i)=>({...l,sourceIndex:i})):[{description:'',quantity:'',lineNet:'',sourceIndex:-1} as Line]});
 const [state,action,pending]=useActionState(packagingAction,{error:'',success:''});
 function line(i:number,key:string,value:string){set(p=>({...p,lines:p.lines.map((l,n)=>i===n?{...l,[key]:value}:l)}));}
 let total:bigint|null=null,net:bigint|null=null;try{total=v.lines.reduce((s,l)=>s+parsePounds(l.lineNet),0n);net=parsePounds(v.net);}catch{/* An incomplete entry stays unknown. */}
 return <form action={action} className="space-y-4"><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={version}/><input type="hidden" name="review" value={JSON.stringify({...v,simpleReview:true,netConfirmed:true})}/>
 <div className="invoice-quick-header"><label>Supplier<select aria-label="Invoice supplier" value={v.supplierId} onChange={e=>set({...v,supplierId:e.target.value,supplierMode:'select'})}><option value="">{suggestedSupplier||'Not found'} · select supplier</option>{suppliers.filter(s=>s.packagingWorkspace).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div><span>Order date</span><strong>{v.orderDate||'Not found'}</strong></div><div><span>Delivery date</span><strong>{v.deliveryDate||'Not found'}</strong></div><div><span>Order number</span><strong>{v.orderNumber||'Not found'}</strong></div></div>
 {!v.supplierId&&v.supplierMode==='select'&&<p className="text-xs text-stone-500">{superUser?'Select a supplier above, or create/enable one in Supplier options below.':'Original saved. You can save a draft while awaiting Super User supplier assignment.'}</p>}
 <div className="overflow-x-auto"><table className="data-table simple-invoice-table"><thead><tr><th>PRODUCT NAME</th><th>QUANTITY</th><th>TOTAL PRICE EXCL. VAT</th></tr></thead><tbody>{v.lines.map((l,i)=><tr key={i}><td><textarea rows={3} aria-label={`Description ${i+1}`} value={l.description} onChange={e=>line(i,'description',e.target.value)} placeholder="Product name"/><button type="button" className="remove-line" aria-label={`Remove product ${i+1}`} onClick={()=>set({...v,lines:v.lines.filter((_,n)=>n!==i)})}>Remove</button></td><td><input aria-label={`quantity ${i+1}`} inputMode="decimal" value={l.quantity} onChange={e=>line(i,'quantity',e.target.value)} placeholder="Not found"/></td><td><input aria-label={`lineNet ${i+1}`} inputMode="decimal" value={l.lineNet} onChange={e=>line(i,'lineNet',e.target.value)} placeholder="Net £"/>{!l.lineNet&&l.printedLineTotal&&<p className="text-xs text-amber-800">Printed £{l.printedLineTotal}; verify VAT basis.</p>}</td></tr>)}</tbody></table></div>
 <button type="button" className="btn btn-secondary" disabled={v.lines.length>=150||pending} onClick={()=>set({...v,lines:[...v.lines,{description:'',quantity:'',lineNet:'',sourceIndex:-1}]})}>Add product</button>
 <div className="flex flex-wrap items-end justify-between gap-3"><p className="text-sm">Product total: <strong>{total===null?'Incomplete':formatGBP(total)}</strong></p><label className="max-w-56">Invoice net total (£)<input aria-label="Invoice net total (£)" inputMode="decimal" value={v.net} onChange={e=>set({...v,net:e.target.value})}/></label></div>
 {total!==null&&net!==null&&total!==net&&<p className="notice" role="alert">Product totals do not match the invoice net total. Correct the amounts before saving.</p>}
 <details className="invoice-optional"><summary>Optional details · dates, order number and notes</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><label>Order date<input type="date" value={v.orderDate} onChange={e=>set({...v,orderDate:e.target.value})}/></label><label>Received / delivery date<input type="date" value={v.deliveryDate} onChange={e=>set({...v,deliveryDate:e.target.value})}/></label><label>Order number<input value={v.orderNumber} onChange={e=>set({...v,orderNumber:e.target.value})}/></label></div><p className="text-xs text-stone-500">Leave absent details blank. Invoices without a delivery date are shown under Undated in Reports, not assigned to an invented week.</p><label className="mt-3">Review explanation<input value={v.reason} onChange={e=>set({...v,reason:e.target.value})}/></label><label className="review-confirmation"><input type="checkbox" checked={v.reconciled} onChange={e=>set({...v,reconciled:e.target.checked})}/>I reviewed any accounting discrepancy and explained it above.</label><label className="review-confirmation"><input type="checkbox" checked={v.duplicateReviewed} onChange={e=>set({...v,duplicateReviewed:e.target.checked})}/>I checked any possible duplicate warning and explained why this is a separate invoice.</label></details>
 {superUser&&<details className="invoice-optional"><summary>Supplier options</summary><div className="mt-3 space-y-3"><label>Supplier action<select aria-label="Supplier action" value={v.supplierMode} onChange={e=>set({...v,supplierMode:e.target.value,supplierId:''})}><option value="select">Use the selected existing supplier</option><option value="enable">Enable Food supplier for Both workspaces</option><option value="create">Create Packaging & Chemicals supplier</option></select></label>{v.supplierMode==='create'&&<label>New supplier name<input aria-label="New supplier name" value={v.newSupplierName} onChange={e=>set({...v,newSupplierName:e.target.value})}/></label>}{v.supplierMode==='enable'&&<label>Food supplier to enable<select aria-label="Food supplier to enable" value={v.supplierId} onChange={e=>set({...v,supplierId:e.target.value})}><option value="">Select…</option>{suppliers.filter(s=>!s.packagingWorkspace).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}</div></details>}
 {superUser&&<details className="invoice-optional"><summary>More details · accounting and categories</summary><div className="grid gap-3 mt-3 sm:grid-cols-3">{(['invoiceNumber','invoiceDate','vat','gross'] as const).map(k=><label key={k}>{({invoiceNumber:'Invoice number',invoiceDate:'Invoice date',vat:'VAT amount (£), if known',gross:'Gross total (£), if known'})[k]}<input aria-label={k} value={v[k]} onChange={e=>set({...v,[k]:e.target.value})}/></label>)}</div><p className="text-xs">Original printed prices/tax information remain in the extracted text. Effective prices are calculated from reviewed net totals and quantities.</p>{v.lines.map((l,i)=><div key={i} className="grid gap-3 mt-3 sm:grid-cols-3"><label>{i+1}. Category<select aria-label={`Category ${i+1}`} value={l.category||'UNCLASSIFIED'} onChange={e=>line(i,'category',e.target.value)}><option value="UNCLASSIFIED">Unclassified · review later</option><option value="PACKAGING">Packaging</option><option value="CHEMICAL">Chemical</option></select></label><label>Unit<input value={l.unit||''} onChange={e=>line(i,'unit',e.target.value)}/></label><label>Pack size<input value={l.packSize||''} onChange={e=>line(i,'packSize',e.target.value)}/></label></div>)}</details>}
 {state.error&&<p role="alert" className="notice">{state.error}</p>}{state.success&&<p role="status">{state.success}</p>}<p className="text-xs text-stone-500">Saving confirms you reviewed the products and their prices exclude VAT. Unknown categories can be organised later in Product Catalogue.</p><div className="flex flex-wrap gap-3"><button className="btn" name="operation" value="confirm" disabled={pending}>{pending?'Saving…':'SAVE INVOICE'}</button><button className="btn btn-secondary" name="operation" value="review" disabled={pending}>Save draft</button></div>
 </form>;
}
