// Real transactional workflow tests against a disposable database, never the user's DATABASE_URL.
import { startPrismaDevServer } from '@prisma/dev';
import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import {randomUUID} from 'node:crypto';
import { spawn } from 'node:child_process';
import assert from 'node:assert/strict';
import {packagingChecks} from './packaging-checks';
import { runOperation } from '../src/lib/operations';
import { saveWeeklyForecast, saveActualSales } from '../src/lib/sales-service';
import { saveTarget, resolveTarget } from '../src/lib/target-service';
import { financialWeek } from '../src/lib/financial-data';
import { dateValue, weekDays } from '../src/lib/dates';
const server = await startPrismaDevServer({ name: `financial-${process.pid}`, persistenceMode: 'stateless', port: 51403, databasePort: 51404, shadowDatabasePort: 51405, streamsPort: 51406 });
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: server.database.connectionString, max: 1 }) });
const monday='2026-09-14', today='2026-09-20';
const admin = {id:'admin',restaurantId:'restaurant',role:'SUPER_USER' as const};
const chef = {id:'chef',restaurantId:'restaurant',role:'CHEF' as const};
const act = (op:string,input:Record<string,unknown>,actor:typeof admin|typeof chef=admin) => runOperation(prisma,actor,op,input,today);
const week = () => prisma.weeklyForecast.findUniqueOrThrow({where:{restaurantId_weekStart:{restaurantId:'restaurant',weekStart:dateValue(monday)}}});
try {
 await new Promise<void>((resolve,reject)=>{ const p=spawn('node',['node_modules/prisma/build/index.js','migrate','deploy'],{env:{...process.env,DATABASE_URL:server.database.connectionString},stdio:'pipe'});let output='';p.stdout.on('data',v=>output+=v);p.stderr.on('data',v=>output+=v);p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(new Error(output))); });
 await prisma.restaurant.create({data:{id:'restaurant',name:'Isolated kitchen',settings:{create:{}}}});
 await prisma.user.createMany({data:[{...admin,name:'Admin',email:'admin@test.example',passwordHash:'unused-test-hash'},{...chef,name:'Chef',email:'chef@test.example',passwordHash:'unused-test-hash'}]});
 await saveWeeklyForecast(prisma,admin,{weekStart:monday,version:0,amounts:Array(7).fill(10000n),reason:''});
 for(const date of weekDays(monday)) await saveActualSales(prisma,admin,{date,version:0,amount:10000n,reason:''},today);
 await act('supplier',{name:'Market',contact:'',email:'',phone:'',deliverySchedule:'Daily'});
 const supplier=await prisma.supplier.findFirstOrThrow();
 await act('product',{name:'Chicken',category:'Meat',countingUnit:'kg',unitCost:'8.1234',supplierId:supplier.id});
 const product=await prisma.product.findFirstOrThrow();
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:today,estimatedAmount:'80.00',notes:'Ten cases'});
 let order=await prisma.supplierOrder.findFirstOrThrow();
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,0n);
 await act('order-status',{id:order.id,stamp:order.updatedAt.toISOString(),status:'PLACED'});
 order=await prisma.supplierOrder.findUniqueOrThrow({where:{id:order.id}});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,8000n);
 await act('receipt',{id:order.id,stamp:order.updatedAt.toISOString(),status:'RECEIVED',reference:'INV-1',accountingDate:today,amount:'100.00'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,0n);
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,10000n);
 await assert.rejects(act('receipt',{id:order.id,stamp:order.updatedAt.toISOString(),status:'RECEIVED',reference:'INV-2',accountingDate:today,amount:'100.00'}));
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:'2026-09-21',estimatedAmount:'40.00',notes:''});
 let cross=await prisma.supplierOrder.findFirstOrThrow({where:{expectedDeliveryDate:dateValue('2026-09-21')}});
 await act('order-status',{id:cross.id,stamp:cross.updatedAt.toISOString(),status:'PLACED'});
 assert.equal((await financialWeek('restaurant','2026-09-21',today,prisma)).commitments,4000n);
 cross=await prisma.supplierOrder.findUniqueOrThrow({where:{id:cross.id}});
 await act('receipt',{id:cross.id,stamp:cross.updatedAt.toISOString(),status:'RECEIVED',reference:'EARLY-DELIVERY',accountingDate:today,amount:'45.00'});
 assert.equal((await financialWeek('restaurant','2026-09-21',today,prisma)).commitments,0n);
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,14500n);
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:today,estimatedAmount:'90.00',notes:''});
 const cancelled=await prisma.supplierOrder.findFirstOrThrow({where:{status:'DRAFT'}});
 await act('order-status',{id:cancelled.id,stamp:cancelled.updatedAt.toISOString(),status:'CANCELLED'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,0n);
 console.log('PASS: draft/cancelled exclusion, placed commitments, atomic receipt, duplicate protection and cross-week delivery');
 let invoice=await prisma.purchaseInvoice.findFirstOrThrow({where:{reference:'INV-1'}});
 await act('invoice-correct',{id:invoice.id,stamp:invoice.updatedAt.toISOString(),amount:'110.00',accountingDate:today,reason:'Supplier corrected invoice'});
 await act('credit',{supplierId:supplier.id,creditForId:invoice.id,reference:'CREDIT-1',accountingDate:today,amount:'10.00',reason:'Returned goods'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,14500n);
 await act('stock-line',{date:today,productId:product.id,quantity:'2.5',stamp:'',reason:''});
 const count=await prisma.stockCount.findFirstOrThrow();
 await act('stock-confirm',{id:count.id,stamp:count.updatedAt.toISOString()});
 await act('product-price',{id:product.id,unitCost:'99.00',previous:'8.1234',reason:'New catalogue price'});
 assert.equal((await prisma.stockCountItem.findFirstOrThrow()).valuePence,2031n);
 assert.equal((await financialWeek('restaurant','2026-09-21',today,prisma)).opening,null); // Opening stock must be entered manually.
 await act('planning',{weekStart:monday,stamp:(await week()).updatedAt.toISOString(),opening:'50.00',expectedClosing:'30.00',nextDelivery:today,followingDelivery:'2026-09-21',sufficient:'on'});
 let data=await financialWeek('restaurant',monday,today,prisma);
 assert.equal(data.finance?.projectedCost,16500n);assert.equal(data.finance?.allowance,300n);assert.equal(data.nextBudget,300n);
 const salesBefore=await prisma.dailySales.findMany();const stockBefore=await prisma.stockCountItem.findMany();const purchasesBefore=await prisma.purchaseInvoice.findMany();
 await saveTarget(prisma,admin,{weekStart:monday,percentage:'23',version:0,reason:''},false,today);
 data=await financialWeek('restaurant',monday,today,prisma);assert.equal(data.finance?.allowance,-400n);assert.equal(data.nextBudget,0n);
 assert.deepEqual(await prisma.dailySales.findMany(),salesBefore);assert.deepEqual(await prisma.stockCountItem.findMany(),stockBefore);assert.deepEqual(await prisma.purchaseInvoice.findMany(),purchasesBefore);
 await assert.rejects(act('planning',{weekStart:monday,stamp:(await week()).updatedAt.toISOString(),opening:'0',expectedClosing:'0',nextDelivery:'',followingDelivery:''},chef),/Only Super Users/);
 await assert.rejects(act('closing-total',{weekStart:monday,stamp:(await week()).updatedAt.toISOString(),amount:'20.31'},chef),/Only Super Users/);
 await act('closing-total',{weekStart:monday,stamp:(await week()).updatedAt.toISOString(),amount:'20.31'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).closing,2031n);
 const beforeEdit=await prisma.supplier.findUniqueOrThrow({where:{id:supplier.id}});
 await act('supplier-edit',{id:supplier.id,previous:JSON.stringify([beforeEdit.name,beforeEdit.contact,beforeEdit.email,beforeEdit.phone,beforeEdit.deliverySchedule,beforeEdit.foodWorkspace,beforeEdit.packagingWorkspace]),name:'Renamed Market',contact:'',email:'',phone:'',deliverySchedule:'Daily'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,14500n);
 await act('purchases-confirm',{weekStart:monday,stamp:(await week()).updatedAt.toISOString()});
 await assert.rejects(act('finalize',{weekStart:monday,stamp:(await week()).updatedAt.toISOString()}));
 await runOperation(prisma,admin,'finalize',{weekStart:monday,stamp:(await week()).updatedAt.toISOString()},'2026-09-21');
 await assert.rejects(saveTarget(prisma,admin,{weekStart:monday,percentage:'22',version:1,reason:'Correction'},false,today),/Reopen/);
 invoice=await prisma.purchaseInvoice.findFirstOrThrow({where:{reference:'INV-1'}});
 await assert.rejects(act('invoice-correct',{id:invoice.id,stamp:invoice.updatedAt.toISOString(),amount:'130.00',accountingDate:today,reason:'Correction'}),/finalized/);
 await act('reopen',{weekStart:monday,stamp:(await week()).updatedAt.toISOString(),reason:'Approved historical correction'});
 await assert.rejects(saveTarget(prisma,admin,{weekStart:monday,percentage:'22.5',version:1,reason:''},false,'2026-09-21'),/reason/);
 await saveTarget(prisma,admin,{weekStart:monday,percentage:'22.5',version:1,reason:'Correct historical target'},false,'2026-09-21');
 assert.equal((await resolveTarget(prisma,'restaurant',monday)).originalBps,2400);
 assert.equal(await prisma.auditLog.count({where:{action:'WEEK_FINALIZED'}}),1);
 await assert.rejects(runOperation(prisma,chef,'product',{name:'Unauthorized'},today),/Only Super Users/);
 // Audit failure must roll back a business mutation, including a newly inserted supplier.
 await assert.rejects(runOperation(prisma,{...admin,id:'missing-actor'},'supplier',{name:'Rollback me',contact:'',email:'',phone:'',deliverySchedule:''},today));
 // Verify rollback from a fresh connection, independently of the failed transaction.
 await prisma.$disconnect();
 assert.equal(await prisma.supplier.count({where:{name:'Rollback me'}}),0);
 await assert.rejects(act('order',{supplierId:supplier.id,expectedDeliveryDate:today,estimatedAmount:'10',notes:'Budget check',status:'PLACED'}),/Budget warning/);
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:today,estimatedAmount:'10',notes:'Budget check',status:'PLACED',acknowledge:'on'});
 const over=await prisma.supplierOrder.findFirstOrThrow({where:{notes:'Budget check'}});
 assert.equal(over.estimatedAmountPence,1000n);
 await act('order-status',{id:over.id,stamp:over.updatedAt.toISOString(),status:'CANCELLED'});
 const beforeReceived=(await financialWeek('restaurant',monday,today,prisma)).purchases;
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:today,estimatedAmount:'8',notes:'Already received',status:'RECEIVED',reference:'DIRECT-RECEIVED',invoiceAmount:'9'});
 const afterReceived=await financialWeek('restaurant',monday,today,prisma);
 assert.equal(afterReceived.purchases,beforeReceived+900n);assert.equal(afterReceived.commitments,0n);
 console.log('PASS: over-budget warning/acknowledgement, unchanged order amount and direct received invoice without double-counting');

 const nextMonday='2026-09-21';
 await saveWeeklyForecast(prisma,admin,{weekStart:nextMonday,version:0,amounts:Array(7).fill(10000n),reason:''});
 const nextWeek=()=>prisma.weeklyForecast.findUniqueOrThrow({where:{restaurantId_weekStart:{restaurantId:'restaurant',weekStart:dateValue(nextMonday)}}});
 await act('stock-plan',{weekStart:nextMonday,stamp:(await nextWeek()).updatedAt.toISOString(),opening:'100',expectedClosing:'50',actualClosing:''});
 const beforeNext=await financialWeek('restaurant',nextMonday,today,prisma);
 const beforeCurrent=(await financialWeek('restaurant',monday,today,prisma)).purchases;
 const purchase={supplierId:supplier.id,orderDate:today,deliveryDate:nextMonday,amount:'25.01',submissionKey:randomUUID()};
 await Promise.all([act('purchase',purchase,chef),act('purchase',purchase,chef)]);
 let simple=await prisma.purchaseInvoice.findUniqueOrThrow({where:{submissionKey:purchase.submissionKey}});
 assert.equal(simple.amountPence,2501n);assert.ok(simple.confirmedAt);assert.equal(simple.orderId,null);
 assert.equal(await prisma.purchaseInvoice.count({where:{submissionKey:purchase.submissionKey}}),1);
 assert.equal((await financialWeek('restaurant',nextMonday,today,prisma)).finance?.allowance,beforeNext.finance!.allowance!-2501n);
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,beforeCurrent);
 const correct={id:simple.id,stamp:simple.updatedAt.toISOString(),supplierId:supplier.id,orderDate:today,deliveryDate:nextMonday,amount:'30',reason:'Correct supplier net total'};
 await assert.rejects(act('purchase-correct',correct,chef),/Only Super Users/);
 await act('purchase-correct',correct);
 await assert.rejects(act('purchase-correct',correct),/Reload/);
 simple=await prisma.purchaseInvoice.findUniqueOrThrow({where:{id:simple.id}});
 assert.equal((await financialWeek('restaurant',nextMonday,today,prisma)).finance?.allowance,beforeNext.finance!.allowance!-3000n);
 await assert.rejects(act('purchase-void',{id:simple.id,stamp:simple.updatedAt.toISOString(),reason:'Duplicate entered'},chef),/Only Super Users/);
 await act('purchase-void',{id:simple.id,stamp:simple.updatedAt.toISOString(),reason:'Duplicate entered'});
 await act('purchase',purchase,chef); // Retrying a voided submission must not recreate it.
 assert.ok((await prisma.purchaseInvoice.findUniqueOrThrow({where:{id:simple.id}})).voidedAt);
 assert.equal((await financialWeek('restaurant',nextMonday,today,prisma)).finance?.allowance,beforeNext.finance!.allowance);
 assert.equal(await prisma.auditLog.count({where:{entityId:simple.id}}),3);
 await prisma.$disconnect();
 assert.equal((await prisma.purchaseInvoice.findUniqueOrThrow({where:{id:simple.id}})).amountPence,3000n);
 assert.equal((await nextWeek()).openingStockPence,10000n);
 await assert.rejects(act('stock-plan',{weekStart:nextMonday,stamp:(await nextWeek()).updatedAt.toISOString(),opening:'100',expectedClosing:'50',actualClosing:'50'}),/week-end|Sunday/);
 await assert.rejects(act('stock-plan',{weekStart:nextMonday,stamp:(await nextWeek()).updatedAt.toISOString(),opening:'100',expectedClosing:'50',actualClosing:''},chef),/Only Super Users/);
 for(const date of weekDays(nextMonday)) await saveActualSales(prisma,admin,{date,version:0,amount:10000n,reason:'Completed week test'},'2026-09-28');
 await runOperation(prisma,admin,'stock-plan',{weekStart:nextMonday,stamp:(await nextWeek()).updatedAt.toISOString(),opening:'100',expectedClosing:'50',actualClosing:'50',reason:'Week-end valuation'},'2026-09-28');
 const final=await financialWeek('restaurant',nextMonday,'2026-09-28',prisma);
 assert.equal(final.finance?.actualCost,5000n);assert.equal(final.finance?.actualBps,714n);assert.equal(final.purchasesComplete,true);
 assert.equal((await nextWeek()).purchasesConfirmedAt,null); // No separate confirmation step.
 await runOperation(prisma,admin,'finalize',{weekStart:nextMonday,stamp:(await nextWeek()).updatedAt.toISOString()},'2026-09-28');
 await assert.rejects(runOperation(prisma,chef,'purchase',{...purchase,submissionKey:randomUUID()},'2026-09-28'),/finalized/);
 assert.equal(await prisma.auditLog.count({where:{action:'WEEK_FINALIZED'}}),2);
 console.log('PASS: combined stock plan, week-end validation, automatic purchase completeness, final food cost and historical lock');
 console.log('PASS: simple net purchases, concurrent retry idempotency, Sunday-to-Monday allocation, corrections/voids, Chef restrictions, audit and persistence across connections');
 console.log('PASS: invoice corrections/credits, stock rounding/snapshots/carry-forward, budgets, target-only recalculation, finalized locks/reopening, audit rollback and Chef permissions');
 await packagingChecks(prisma);
} finally {await prisma.$disconnect();await server.close();}
