// Real transactional workflow tests against a disposable database, never the user's DATABASE_URL.
import { startPrismaDevServer } from '@prisma/dev';
import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { spawn } from 'node:child_process';
import assert from 'node:assert/strict';
import { runOperation } from '../src/lib/operations';
import { saveWeeklyForecast, saveActualSales } from '../src/lib/sales-service';
import { saveTarget, resolveTarget } from '../src/lib/target-service';
import { financialWeek } from '../src/lib/financial-data';
import { dateValue, weekDays } from '../src/lib/dates';
const server = await startPrismaDevServer({ name: `financial-${process.pid}`, persistenceMode: 'stateless', port: 51403, databasePort: 51404, shadowDatabasePort: 51405, streamsPort: 51406 });
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: server.database.connectionString }) });
const monday='2026-09-14', today='2026-09-20';
const admin = {id:'admin',restaurantId:'restaurant',role:'SUPER_USER' as const};
const chef = {id:'chef',restaurantId:'restaurant',role:'CHEF' as const};
const act = (op:string,input:Record<string,unknown>,actor=admin) => runOperation(prisma,actor,op,input,today);
const week = () => prisma.weeklyForecast.findUniqueOrThrow({where:{restaurantId_weekStart:{restaurantId:'restaurant',weekStart:dateValue(monday)}}});
try {
 await new Promise<void>((resolve,reject)=>{ const p=spawn('node',['node_modules/prisma/build/index.js','migrate','deploy'],{env:{...process.env,DATABASE_URL:server.database.connectionString},stdio:'pipe'});let output='';p.stdout.on('data',v=>output+=v);p.stderr.on('data',v=>output+=v);p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(new Error(output))); });
 await prisma.restaurant.create({data:{id:'restaurant',name:'Isolated kitchen',settings:{create:{}}}});
 await prisma.user.createMany({data:[{...admin,name:'Admin',email:'admin@test.example',passwordHash:'unused-test-hash'},{...chef,name:'Chef',email:'chef@test.example',passwordHash:'unused-test-hash'}]});
 await saveWeeklyForecast(prisma,admin,{weekStart:monday,version:0,amounts:Array(7).fill(10000n),reason:''});
 for(const date of weekDays(monday)) await saveActualSales(prisma,admin,{date,version:0,amount:10000n,reason:''},today);
 await act('supplier',{name:'Market',contact:'',email:'',phone:'',deliverySchedule:'Daily'});
 const supplier=await prisma.supplier.findFirstOrThrow();
 await act('product',{name:'Chicken',category:'Meat',countingUnit:'kg',unitCost:'8.1234',supplierId:supplier.id});
 const product=await prisma.product.findFirstOrThrow();
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:today,estimatedAmount:'80.00',notes:'Ten cases'});
 let order=await prisma.supplierOrder.findFirstOrThrow();
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,0n);
 await act('order-status',{id:order.id,stamp:order.updatedAt.toISOString(),status:'PLACED'});
 order=await prisma.supplierOrder.findUniqueOrThrow({where:{id:order.id}});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,8000n);
 await act('receipt',{id:order.id,stamp:order.updatedAt.toISOString(),status:'RECEIVED',reference:'INV-1',accountingDate:today,amount:'100.00'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,0n);
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,10000n);
 await assert.rejects(act('receipt',{id:order.id,stamp:order.updatedAt.toISOString(),status:'RECEIVED',reference:'INV-2',accountingDate:today,amount:'100.00'}));
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:'2026-09-21',estimatedAmount:'40.00',notes:''});
 let cross=await prisma.supplierOrder.findFirstOrThrow({where:{expectedDeliveryDate:dateValue('2026-09-21')}});
 await act('order-status',{id:cross.id,stamp:cross.updatedAt.toISOString(),status:'PLACED'});
 assert.equal((await financialWeek('restaurant','2026-09-21',today,prisma)).commitments,4000n);
 cross=await prisma.supplierOrder.findUniqueOrThrow({where:{id:cross.id}});
 await act('receipt',{id:cross.id,stamp:cross.updatedAt.toISOString(),status:'RECEIVED',reference:'EARLY-DELIVERY',accountingDate:today,amount:'45.00'});
 assert.equal((await financialWeek('restaurant','2026-09-21',today,prisma)).commitments,0n);
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,14500n);
 await act('order',{supplierId:supplier.id,expectedDeliveryDate:today,estimatedAmount:'90.00',notes:''});
 const cancelled=await prisma.supplierOrder.findFirstOrThrow({where:{status:'DRAFT'}});
 await act('order-status',{id:cancelled.id,stamp:cancelled.updatedAt.toISOString(),status:'CANCELLED'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).commitments,0n);
 console.log('PASS: draft/cancelled exclusion, placed commitments, atomic receipt, duplicate protection and cross-week delivery');
 let invoice=await prisma.purchaseInvoice.findFirstOrThrow({where:{reference:'INV-1'}});
 await act('invoice-correct',{id:invoice.id,stamp:invoice.updatedAt.toISOString(),amount:'110.00',accountingDate:today,reason:'Supplier corrected invoice'});
 await act('credit',{supplierId:supplier.id,creditForId:invoice.id,reference:'CREDIT-1',accountingDate:today,amount:'10.00',reason:'Returned goods'});
 assert.equal((await financialWeek('restaurant',monday,today,prisma)).purchases,14500n);
 await act('stock-line',{date:today,productId:product.id,quantity:'2.5',stamp:'',reason:''});
 const count=await prisma.stockCount.findFirstOrThrow();
 await act('stock-confirm',{id:count.id,stamp:count.updatedAt.toISOString()});
 await act('product-price',{id:product.id,unitCost:'99.00',previous:'8.1234',reason:'New catalogue price'});
 assert.equal((await prisma.stockCountItem.findFirstOrThrow()).valuePence,2031n);
 assert.equal((await financialWeek('restaurant','2026-09-21',today,prisma)).opening,2031n);
 await act('planning',{weekStart:monday,stamp:(await week()).updatedAt.toISOString(),opening:'50.00',expectedClosing:'30.00',nextDelivery:today,followingDelivery:'2026-09-21',sufficient:'on'});
 let data=await financialWeek('restaurant',monday,today,prisma);
 assert.equal(data.finance?.projectedCost,16500n);assert.equal(data.finance?.allowance,300n);assert.equal(data.nextBudget,300n);
 const salesBefore=await prisma.dailySales.findMany();const stockBefore=await prisma.stockCountItem.findMany();const purchasesBefore=await prisma.purchaseInvoice.findMany();
 await saveTarget(prisma,admin,{weekStart:monday,percentage:'23',version:0,reason:''},false,today);
 data=await financialWeek('restaurant',monday,today,prisma);assert.equal(data.finance?.allowance,-400n);assert.equal(data.nextBudget,0n);
 assert.deepEqual(await prisma.dailySales.findMany(),salesBefore);assert.deepEqual(await prisma.stockCountItem.findMany(),stockBefore);assert.deepEqual(await prisma.purchaseInvoice.findMany(),purchasesBefore);
 await act('purchases-confirm',{weekStart:monday,stamp:(await week()).updatedAt.toISOString()});
 await act('finalize',{weekStart:monday,stamp:(await week()).updatedAt.toISOString()});
 await assert.rejects(saveTarget(prisma,admin,{weekStart:monday,percentage:'22',version:1,reason:'Correction'},false,today),/Reopen/);
 invoice=await prisma.purchaseInvoice.findFirstOrThrow({where:{reference:'INV-1'}});
 await assert.rejects(act('invoice-correct',{id:invoice.id,stamp:invoice.updatedAt.toISOString(),amount:'130.00',accountingDate:today,reason:'Correction'}),/finalized/);
 await act('reopen',{weekStart:monday,stamp:(await week()).updatedAt.toISOString(),reason:'Approved historical correction'});
 await assert.rejects(saveTarget(prisma,admin,{weekStart:monday,percentage:'22.5',version:1,reason:''},false,'2026-09-21'),/reason/);
 await saveTarget(prisma,admin,{weekStart:monday,percentage:'22.5',version:1,reason:'Correct historical target'},false,'2026-09-21');
 assert.equal((await resolveTarget(prisma,'restaurant',monday)).originalBps,2400);
 assert.equal(await prisma.auditLog.count({where:{action:'WEEK_FINALIZED'}}),1);
 await assert.rejects(runOperation(prisma,chef,'product',{name:'Unauthorized'},today),/Only Super Users/);
 // Audit failure must roll back a business mutation, including a newly inserted supplier.
 await assert.rejects(runOperation(prisma,{...admin,id:'missing-actor'},'supplier',{name:'Rollback me',contact:'',email:'',phone:'',deliverySchedule:''},today));
 // Verify rollback from a fresh connection, independently of the failed transaction.
 await prisma.$disconnect();
 assert.equal(await prisma.supplier.count({where:{name:'Rollback me'}}),0);
 console.log('PASS: invoice corrections/credits, stock rounding/snapshots/carry-forward, budgets, target-only recalculation, finalized locks/reopening, audit rollback and Chef permissions');
} finally {await prisma.$disconnect();await server.close();}
