import {expect,type Page,type Browser} from '@playwright/test';
import {fileFirstBrowser} from './file-first-browser';
import {createCanvas} from '@napi-rs/canvas';
import type {PrismaClient} from '../src/generated/prisma/client';
export async function packagingBrowser(page:Page,chefPage:Page,browser:Browser,prisma:PrismaClient){
 const base='http://localhost:3137';
 await page.emulateMedia({reducedMotion:'reduce'});
 await fileFirstBrowser(page,chefPage,prisma);
 const confirmedBefore=await prisma.packagingInvoice.count({where:{status:'CONFIRMED'}}),linesBefore=await prisma.packagingLine.count();
 await page.goto(base+'/packaging/suppliers');await page.getByText('Add supplier',{exact:true}).click();
 const supplierForm=page.locator('form').filter({has:page.getByRole('button',{name:'Create supplier',exact:true})});
 await supplierForm.getByLabel('Workspace',{exact:true}).selectOption('PACKAGING');await supplierForm.getByLabel('Supplier name',{exact:true}).fill('Clean & Pack');await supplierForm.getByRole('button',{name:'Create supplier',exact:true}).click();await expect(page.getByRole('heading',{name:'Clean & Pack',exact:true})).toBeVisible();
 await chefPage.goto(base+'/orders');await expect(chefPage.locator('option').filter({hasText:'Clean & Pack'})).toHaveCount(0);
 await chefPage.goto(base+'/packaging/invoices');await expect(chefPage.getByRole('button',{name:'Create supplier',exact:true})).toHaveCount(0);
 const canvas=createCanvas(1400,530),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1400,530);ctx.fillStyle='black';ctx.font='28px Arial';['Supplier: Clean & Pack','Invoice No: BROWSER-1','Description Qty Unit Price ex VAT Line Total','Washing Liquid 2 bottle 8.00 16.00','Net total: 16.00','VAT: 3.20','Gross total: 19.20'].forEach((s,i)=>ctx.fillText(s,25,45+i*65));
 await chefPage.locator('input[type=file]').setInputFiles({name:'invoice.png',mimeType:'image/png',buffer:canvas.toBuffer('image/png')});
 await chefPage.getByRole('button',{name:'Upload & review invoice',exact:true}).click();
 await expect(chefPage).toHaveURL(/\/packaging\/invoices\/[^/]+$/,{timeout:120000});
 await expect(chefPage.getByLabel('Invoice supplier',{exact:true})).toHaveValue((await prisma.supplier.findFirstOrThrow({where:{name:'Clean & Pack'}})).id);
 await expect(chefPage.getByLabel('Invoice net total (£)',{exact:true})).toHaveValue('16.00');
 await expect(chefPage.getByLabel('VAT amount (£), if known',{exact:true})).toHaveValue('3.20');
 await expect(chefPage.getByLabel('Description 1',{exact:true})).toHaveValue('Washing Liquid');
 await chefPage.getByLabel('Category 1',{exact:true}).selectOption('CHEMICAL');await chefPage.getByLabel('packSize 1',{exact:true}).fill('5l');
 await chefPage.screenshot({path:'/tmp/cocotte-packaging-review-phone.png',fullPage:true,caret:'initial'});
 const invoiceId=chefPage.url().split('/').at(-1)!;
 expect(await prisma.packagingLine.count()).toBe(linesBefore);
 await chefPage.getByRole('button',{name:'Confirm Invoice',exact:true}).click();await expect(chefPage.locator('form').getByRole('alert')).toContainText('exclude VAT');
 await chefPage.getByText('I checked the original and confirm all line amounts and the invoice net total EXCLUDE VAT.',{exact:true}).click();
 await chefPage.getByRole('button',{name:'Confirm Invoice',exact:true}).click();
 await expect(chefPage.getByRole('heading',{name:'Confirmed net spending · £16.00',exact:true})).toBeVisible();
 await chefPage.reload();await expect(chefPage.getByRole('heading',{name:'Confirmed net spending · £16.00',exact:true})).toBeVisible();
 expect(await prisma.packagingInvoice.count({where:{status:'CONFIRMED'}})).toBe(confirmedBefore+1);expect(await prisma.packagingLine.count()).toBe(linesBefore+1);
 const downloaded=await chefPage.request.get(base+`/packaging/invoices/${invoiceId}/document`);expect(downloaded.status()).toBe(200);expect(downloaded.headers()['content-type']).toBe('image/png');expect((await downloaded.body()).length).toBeGreaterThan(1000);
 const anonymous=await browser.newContext();const forbidden=await anonymous.request.get(base+`/packaging/invoices/${invoiceId}/document`,{maxRedirects:0});expect([302,303,307]).toContain(forbidden.status());await anonymous.close();
 await page.goto(base+`/packaging/invoices/${invoiceId}`);await expect(page.getByRole('heading',{name:'Confirmed net spending · £16.00',exact:true})).toBeVisible();
 await chefPage.getByLabel('Workspace',{exact:true}).filter({visible:true}).selectOption('food');await expect(chefPage).toHaveURL(/\/dashboard$/);await expect(chefPage.getByText('£99.50',{exact:true}).first()).toBeVisible();
 const product=(await prisma.packagingLine.findFirstOrThrow({where:{invoiceId}})).productId;
 const routes=['/packaging','/packaging/invoices','/packaging/products','/packaging/reports','/packaging/suppliers',`/packaging/products/${product}`,`/packaging/invoices/${invoiceId}`];
 for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});for(const route of routes){await page.goto(base+route);await expect(page.locator('main')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${route} at ${width}px`).toBe(true);}}
 await page.goto(base+'/packaging/reports');await expect(page.locator('.recharts-surface').first()).toBeVisible();await expect(page.getByRole('row').filter({hasText:'Washing Liquid'})).toContainText('£16.00');await page.screenshot({path:'/tmp/cocotte-packaging-reports-desktop.png',fullPage:true,caret:'initial'});
 await chefPage.goto(base+'/packaging');await chefPage.screenshot({path:'/tmp/cocotte-packaging-dashboard-phone.png',fullPage:true,caret:'initial'});
 await chefPage.goto(base+'/packaging/suppliers');await expect(chefPage.getByRole('button',{name:'Create supplier',exact:true})).toHaveCount(0);await expect(chefPage.getByRole('button',{name:'Deactivate supplier',exact:true})).toHaveCount(0);
 console.log('PASS: production OCR upload/review/confirmation, authenticated original file, shared-device persistence, workspace switch, unchanged food allowance, real reports/charts and responsive packaging pages');
}
