// Isolated end-to-end check: no DATABASE_URL from the user's environment is used.
import { startPrismaDevServer } from '@prisma/dev';
import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { chromium, expect } from '@playwright/test';
import { spawn, type ChildProcess } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import {packagingBrowser} from './packaging-browser';
import { londonToday, mondayOf, weekDays, dayLabel, dateValue } from '../src/lib/dates';

const adminEmail = 'admin@smoke.example';
const chefEmail = 'chef@smoke.example';
const password = randomBytes(24).toString('base64url');
const server = await startPrismaDevServer({ name: `restaurant-smoke-${process.pid}`, persistenceMode: 'stateless', port: 51383, databasePort: 51384, shadowDatabasePort: 51385, streamsPort: 51386 });
const url = server.database.connectionString;
const env = { ...process.env, DATABASE_URL: url, DATABASE_POOL_SIZE: '1', SEED_ADMIN_EMAIL: adminEmail, SEED_ADMIN_PASSWORD: password, SEED_ADMIN_NAME: 'Smoke Admin', RESTAURANT_NAME: 'Smoke Test Kitchen' };
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: url, max: 1 }) });
let app: ChildProcess | undefined;
let appLog = '';
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
async function command(bin: string, args: string[]) {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(bin, args, { env, stdio: ['ignore', 'pipe', 'pipe'] });
    let output = ''; child.stdout.on('data', chunk => { output += chunk; }); child.stderr.on('data', chunk => { output += chunk; });
    child.on('error', reject); child.on('exit', code => code === 0 ? resolve() : reject(new Error(`${bin} failed: ${output}`)));
  });
}
try {
  await command('node', ['node_modules/prisma/build/index.js', 'migrate', 'deploy']);
  await command('node', ['--import', 'tsx', 'prisma/seed.ts']);
  console.log('PASS: committed migration and administrator seed through PostgreSQL wire protocol');
  app = spawn('node', ['node_modules/next/dist/bin/next', 'start', '--hostname', '127.0.0.1', '--port', '3137'], { env, stdio: ['ignore', 'pipe', 'pipe'] });
  app.stdout?.on('data', c => { appLog += c; }); app.stderr?.on('data', c => { appLog += c; });
  for (let n = 0; n < 100; n++) {
    try { if ((await fetch('http://localhost:3137/login')).ok) break; } catch { /* wait for startup */ }
    if (n === 99) throw new Error(`App did not start: ${appLog}`);
    await new Promise(resolve => setTimeout(resolve, 200));
  }
  const chrome = process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  browser = await chromium.launch({ headless: true, ...(existsSync(chrome) ? { executablePath: chrome } : {}) });
  const page = await browser.newPage();
  const browserErrors:string[]=[];
  page.on('pageerror',e=>browserErrors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')browserErrors.push(`${m.text()} at ${m.location().url}`);});
  await page.goto('http://localhost:3137/admin/users');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Email address').fill(adminEmail);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in to your kitchen' }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible();
  await page.goto('http://localhost:3137/admin/users');
  await page.getByLabel('Full name').fill('Smoke Chef');
  await page.getByLabel('Email', { exact: true }).fill(chefEmail);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.getByText('User created.', { exact: false })).toBeVisible();
  expect(await prisma.auditLog.count({ where: { action: 'USER_CREATED' } })).toBe(1);
  console.log('PASS: administrator login, account creation and transactional audit');
  const chefContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true });
  const chefPage = await chefContext.newPage();
  chefPage.on('pageerror',e=>browserErrors.push(e.message));
  chefPage.on('console',m=>{if(m.type()==='error')browserErrors.push(`${m.text()} at ${m.location().url}`);});
  await chefPage.goto('http://localhost:3137/login');
  await chefPage.getByLabel('Email address').fill(chefEmail);
  await chefPage.getByLabel('Password', { exact: true }).fill(password);
  await chefPage.getByRole('button', { name: 'Sign in to your kitchen' }).click();
  await expect(chefPage.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible();
  await chefPage.goto('http://localhost:3137/admin/users');
  await expect(chefPage).toHaveURL(/\/dashboard$/);
  expect(await chefPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const today = londonToday();
  const monday = mondayOf(today);
  await page.goto(`http://localhost:3137/admin/forecasts?week=${monday}`);
  for (const date of weekDays(monday)) await page.getByLabel(`${dayLabel(date)} (£)`, { exact: true }).fill('100.00');
  await page.getByRole('button', { name: 'Create weekly forecast' }).click();
  await expect(page.getByRole('status')).toHaveText('Weekly forecast saved.');
  await chefPage.goto(`http://localhost:3137/sales?date=${today}`);
  await chefPage.getByLabel(`Actual sales for ${dayLabel(today)} (£)`, { exact: true }).fill('50.00');
  const salesForm = chefPage.locator('form').filter({ has: chefPage.getByLabel(`Actual sales for ${dayLabel(today)} (£)`, { exact: true }) });
  await salesForm.getByRole('button', { name: 'Record actual sales' }).click();
  await expect(chefPage.getByText('Recorded: £50.00.', { exact: false })).toBeVisible();
  await page.getByLabel(`${dayLabel(today)} (£)`, { exact: true }).fill('200.00');
  await page.getByLabel('Reason for change').fill('Revised booking forecast');
  await page.getByRole('button', { name: 'Save forecast changes' }).click();
  await expect(page.getByRole('status')).toHaveText('Weekly forecast saved.');
  await expect.poll(async () => (await prisma.weeklyForecast.findUniqueOrThrow({ where: { restaurantId_weekStart: { restaurantId: 'restaurant', weekStart: dateValue(monday) } } })).version).toBe(2);
  const saved = await prisma.weeklyForecast.findUniqueOrThrow({ where: { restaurantId_weekStart: { restaurantId: 'restaurant', weekStart: dateValue(monday) } }, include: { days: true } });
  expect(saved.version).toBe(2);
  expect(saved.days.every(day => day.originalForecastPence === 10000n)).toBe(true);
  await chefPage.goto(`http://localhost:3137/dashboard?week=${monday}`);
  await expect(chefPage.getByText('£650.00', { exact: true })).toBeVisible();
  await chefPage.goto('http://localhost:3137/admin/forecasts');
  await expect(chefPage).toHaveURL(/\/dashboard$/);
  expect(await prisma.auditLog.count({ where: { action: { in: ['FORECAST_CREATED', 'FORECAST_UPDATED', 'SALES_RECORDED'] } } })).toBe(3);
  console.log('PASS: forecasts, immutable originals, Chef sales, projections, audit and forecast permissions');
  const originalSales = await prisma.dailySales.findMany();
  await page.goto(`http://localhost:3137/admin/food-cost?week=${monday}`);
  await page.getByLabel('Weekly target (%)', { exact: true }).fill('23');
  await page.getByRole('button', { name: 'Save weekly target', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Food cost target saved.');
  await expect.poll(async () => (await prisma.weeklyTarget.findFirst({ where: { weekStart: dateValue(monday) } }))?.targetBps).toBe(2300);
  expect(await prisma.dailySales.findMany()).toEqual(originalSales);
  await chefPage.goto(`http://localhost:3137/dashboard?week=${monday}`);
  await expect(chefPage.getByText('23%', { exact: true })).toBeVisible();
  await chefPage.goto('http://localhost:3137/admin/food-cost');
  await expect(chefPage).toHaveURL(/\/dashboard$/);
  expect(await prisma.auditLog.count({ where: { action: 'WEEKLY_TARGET_CHANGED' } })).toBe(1);
  console.log('PASS: weekly target settings, Chef read-only access, audit and sales preservation');
  await chefPage.goto('http://localhost:3137/orders');
  await page.goto('http://localhost:3137/suppliers');
  await page.getByText('Add supplier', { exact: true }).click();
  await page.getByLabel('Supplier name', { exact: true }).fill('Fresh Market');
  await page.getByRole('button', { name: 'Create supplier', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Fresh Market', exact: true })).toBeVisible();
  await chefPage.evaluate(()=>window.dispatchEvent(new Event('focus')));
  await expect(chefPage.locator('option').filter({hasText:'Fresh Market'}).first()).toBeAttached();
  await page.goto('http://localhost:3137/stock');
  await page.getByText('Add catalogue product', { exact: true }).click();
  const productForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Create product', exact: true }) });
  await productForm.getByLabel('Product name', { exact: true }).fill('Potatoes');
  await productForm.getByLabel('Category', { exact: true }).fill('Produce');
  await productForm.getByLabel('Counting unit (kg, case, litre…)', { exact: true }).fill('kg');
  await productForm.getByLabel('Cost per counting unit (£, up to four decimals)', { exact: true }).fill('1.2500');
  await productForm.getByLabel('Supplier', { exact: true }).selectOption({ label: 'Fresh Market' });
  await productForm.getByRole('button', { name: 'Create product', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Potatoes', exact: true })).toBeVisible();
  await chefPage.goto('http://localhost:3137/orders');
  const purchaseForm=chefPage.locator('form').filter({has:chefPage.getByRole('button',{name:'Save Purchase',exact:true})});
  await purchaseForm.getByLabel('Supplier name',{exact:true}).selectOption({label:'Fresh Market'});
  await purchaseForm.getByLabel('Total amount EXCLUDING VAT (£)',{exact:true}).fill('25.00');
  await purchaseForm.getByRole('button',{name:'Save Purchase',exact:true}).click();
  await expect(chefPage.getByRole('status')).toContainText('Purchase saved and confirmed');
  await expect(chefPage.getByRole('row').filter({hasText:'Fresh Market'})).toContainText('£25.00');
  expect(await prisma.purchaseInvoice.count()).toBe(1);
  expect(await prisma.supplierOrder.count()).toBe(0);
  const purchase=await prisma.purchaseInvoice.findFirstOrThrow();
  expect(purchase.amountPence).toBe(2500n);expect(purchase.confirmedAt).not.toBeNull();
  await chefPage.reload();
  await expect(chefPage.getByRole('row').filter({hasText:'Fresh Market'})).toContainText('£25.00');
  await page.goto(`http://localhost:3137/admin/planning?week=${monday}`);
  const planningForm = page.locator('form').filter({ has: page.getByLabel('Opening stock (£)', { exact: true }) });
  await planningForm.getByLabel('Opening stock (£)', { exact: true }).fill('100');
  await planningForm.getByLabel('Expected Sunday closing stock (£)', { exact: true }).fill('50');
  await planningForm.getByRole('button', { name: 'Save stock plan', exact: true }).click();
  await expect(planningForm.getByRole('status')).toHaveText('Saved successfully.');
  await page.goto(`http://localhost:3137/dashboard?week=${monday}`);
  await expect(page.getByText('£74.50', { exact: true }).first()).toBeVisible();
  await page.screenshot({ path: '/tmp/cocotte-populated-dashboard.png', fullPage: true, caret: 'initial' });
  await chefPage.emulateMedia({ reducedMotion: 'reduce' });
  for (const route of ['/dashboard', '/sales', '/orders', '/stock', '/suppliers', '/reports']) {
    await chefPage.goto(`http://localhost:3137${route}`);
    await expect(chefPage.locator('main')).toBeVisible();
    expect(await chefPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  }
  await page.goto('http://localhost:3137/reports');
  await expect(page.locator('.recharts-surface').first()).toBeVisible();
  for(const tab of ['sales','purchasing','suppliers','history']) {
    await chefPage.goto(`http://localhost:3137/reports?week=${monday}&tab=${tab}`);
    expect(await chefPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    const exported=await chefPage.request.get(`http://localhost:3137/reports/export?week=${monday}&tab=${tab}`);expect(exported.status()).toBe(200);
  }
  await page.goto(`http://localhost:3137/reports?week=${monday}&tab=suppliers`);
  await expect(page.locator('.recharts-surface')).toBeVisible();
  await page.screenshot({path:'/tmp/cocotte-supplier-report.png',fullPage:true,caret:'initial'});
  const csv = await page.request.get(`http://localhost:3137/reports/export?week=${monday}&tab=history`);
  expect(csv.status()).toBe(200); expect(await csv.text()).toContain('Target %');
  console.log('PASS: supplier/product creation, mobile confirmed purchase, reload persistence, reports/CSV and mobile overflow checks');
  for(const width of [320,390,768,1024,1440]) {
    await page.setViewportSize({width,height:900});
    for(const route of ['/dashboard','/sales','/orders','/suppliers','/admin/planning','/admin/food-cost','/admin/users','/admin','/stock','/reports?tab=sales','/reports?tab=purchasing','/reports?tab=suppliers','/reports?tab=history']) {
      await page.goto(`http://localhost:3137${route}`);
      await expect(page.locator('main')).toBeVisible();
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${route} at ${width}px`).toBe(true);
    }
  }
  await page.goto('http://localhost:3137/orders');
  await page.screenshot({path:'/tmp/cocotte-simple-purchases-desktop.png',fullPage:true,caret:'initial'});
  await chefPage.goto('http://localhost:3137/orders');
  await chefPage.screenshot({path:'/tmp/cocotte-simple-purchases-phone.png',fullPage:true,caret:'initial'});
  console.log('PASS: all screens at phone, tablet, laptop and desktop widths without page overflow');
  await page.goto('http://localhost:3137/orders');
  await page.locator('details.purchase-review summary').first().click();
  const correction=page.locator('form').filter({has:page.getByRole('button',{name:'Save correction',exact:true})});
  await correction.getByLabel('Corrected total EXCLUDING VAT (£)').fill('30');
  await correction.getByLabel('Reason for correction').fill('Correct net purchase total');
  await correction.getByRole('button',{name:'Save correction',exact:true}).click();
  await expect(correction.getByRole('status')).toContainText('Saved successfully');
  await chefPage.goto('http://localhost:3137/dashboard');
  await expect(chefPage.getByText('£69.50',{exact:true}).first()).toBeVisible();
  await page.getByLabel('Reason to void purchase').fill('Entered purchase in error');
  await page.getByRole('button',{name:'Void purchase',exact:true}).click();
  await expect(page.getByRole('row').filter({hasText:'Fresh Market'})).toContainText('Voided');
  await chefPage.reload();
  await expect(chefPage.getByText('£99.50',{exact:true}).first()).toBeVisible();
  expect(await prisma.purchaseInvoice.count()).toBe(1);
  expect((await prisma.purchaseInvoice.findFirstOrThrow()).voidedAt).not.toBeNull();
  console.log('PASS: Super User purchase correction/void and immediate cross-device allowance refresh');
  await packagingBrowser(page,chefPage,browser,prisma);
  await page.goto('http://localhost:3137/admin/users');
  await page.getByRole('button', { name: 'Deactivate' , exact: true }).click();
  await expect(page.getByText('Chef · Inactive')).toBeVisible();
  await chefPage.reload(); await expect(chefPage).toHaveURL(/\/login$/);
  console.log('PASS: mobile Chef login, admin route denied, deactivation revokes session');
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.goto('http://localhost:3137/dashboard'); await expect(page).toHaveURL(/\/login$/);
  if(browserErrors.length) console.log('Test server diagnostics:',appLog);
  expect(browserErrors).toEqual([]);
  console.log('PASS: logout revokes administrator session; no browser runtime/hydration errors');
} catch (error) { console.log('Test server diagnostics:',appLog); throw error; } finally {
  await browser?.close();
  if (app && app.exitCode === null) { app.kill('SIGTERM'); await new Promise<void>(resolve => { app!.once('exit', () => resolve()); setTimeout(resolve, 5000); }); }
  await prisma.$disconnect(); await server.close();
}
