import Link from 'next/link';
import { requireAdmin } from '@/lib/auth';
import { londonToday, mondayOf, addDays } from '@/lib/dates';
import { selectedWeek } from '@/lib/week-data';
import { financialWeek } from '@/lib/financial-data';
import { poundsInput } from '@/lib/money';
import { ForecastForm } from '@/components/forecast-form';
import { TargetForm } from '@/components/target-form';
import { OperationForm } from '@/components/operation-form';
import { WeekNavigation } from '@/components/week-navigation';
export default async function Planning({searchParams}:{searchParams:Promise<{week?:string|string[]}>}) {
  const user=await requireAdmin(); const today=londonToday(); const monday=selectedWeek((await searchParams).week,today);
  const {week,days,target}=await financialWeek(user.restaurantId,monday,today);
  const input=(v:bigint|null|undefined)=>v==null?'':poundsInput(v);
  return <><p className="eyebrow">Super User · Monday–Sunday</p><h1 className="page-title">Weekly Planning</h1><WeekNavigation monday={monday} path="/admin/planning" current={mondayOf(today)}/>{week?.finalizedAt?<p className="card">This week is finalized. <Link href={`/reports?week=${monday}&tab=purchasing`}>Open its report to request an audited reopening.</Link></p>:<><section className="card mb-5"><h2 className="section-title">Daily net sales forecast</h2><p className="mb-4 text-sm text-stone-500">The original seven-day forecast is preserved and used for unrecorded days. Later forecast revisions remain available in the audit history.</p><ForecastForm key={monday} monday={monday} version={week?.version??0} amounts={days.length?days.map(d=>input(d.forecastPence)):Array(7).fill('')}/></section><div className="grid gap-5 lg:grid-cols-3"><section className="card"><h2 className="section-title">Food cost target</h2><p className="mb-4 text-sm">{target.source==='DEFAULT'?'Inherited default':'Weekly target'} · Applies only to this week.</p><TargetForm key={monday} monday={monday} targetBps={target.targetBps} version={target.version} historical={monday<mondayOf(today)}/><Link className="mt-5 block text-sm underline" href={`/admin/food-cost?week=${monday}`}>Default settings, scheduled targets & history</Link></section><section className="card stock-plan lg:col-span-2"><h2 className="section-title">Weekly stock planning</h2><p className="mb-3 text-xs text-stone-500">One manual opening value per week. No daily or product counts are required.</p>{week?<OperationForm key={monday} operation="stock-plan" hidden={{weekStart:monday,stamp:week.updatedAt.toISOString(),...(addDays(monday,6)>today?{actualClosing:''}:{})}} fields={[{name:'opening',label:'Opening stock (£)',value:input(week.openingStockPence)},{name:'expectedClosing',label:'Expected Sunday closing stock (£)',value:input(week.expectedClosingStockPence)},{name:'actualClosing',label:'Actual Sunday closing stock (£)',value:input(week.actualClosingStockPence),required:false,disabled:addDays(monday,6)>today,hint:addDays(monday,6)>today?'Available at week-end.':'Leave blank until the actual valuation is known.'},{name:'reason',label:'Reason for historical change or correction',required:addDays(monday,6)<today}]} button="Save stock plan"/>:<p>Create the seven-day forecast first.</p>}</section></div></>}<Link className="mt-6 block text-sm underline" href={`/stock?week=${monday}`}>Optional product catalogue and detailed stock counts</Link></>;
}
