import Link from 'next/link';
import { requireAdmin } from '@/lib/auth';
import { londonToday, mondayOf, addDays } from '@/lib/dates';
import { selectedWeek } from '@/lib/week-data';
import { financialWeek } from '@/lib/financial-data';
import { poundsInput } from '@/lib/money';
import { ForecastForm } from '@/components/forecast-form';
import { TargetForm } from '@/components/target-form';
import { OperationForm } from '@/components/operation-form';
import { WeekNavigation } from '@/components/week-navigation';
export default async function Planning({searchParams}:{searchParams:Promise<{week?:string|string[]}>}) {
  const user=await requireAdmin(); const today=londonToday(); const monday=selectedWeek((await searchParams).week,today);
  const {week,days,target}=await financialWeek(user.restaurantId,monday,today);
  const input=(v:bigint|null|undefined)=>v==null?'':poundsInput(v);
  return <><p className="eyebrow">Super User · Monday–Sunday</p><h1 className="page-title">Weekly Planning</h1><WeekNavigation monday={monday} path="/admin/planning" current={mondayOf(today)}/>{week?.finalizedAt?<p className="card">This week is finalized. <Link href={`/reports?week=${monday}&tab=purchasing`}>Open its report to request an audited reopening.</Link></p>:<><section className="card mb-5"><h2 className="section-title">Daily net sales forecast</h2><p className="mb-4 text-sm text-stone-500">The original seven-day forecast is preserved and used for unrecorded days. Later forecast revisions remain available in the audit history.</p><ForecastForm key={monday} monday={monday} version={week?.version??0} amounts={days.length?days.map(d=>input(d.forecastPence)):Array(7).fill('')}/></section><div className="grid gap-5 lg:grid-cols-2"><section className="card"><h2 className="section-title">Food cost target</h2><p className="mb-4 text-sm">{target.source==='DEFAULT'?'Inherited default':'Weekly target'} · Applies only to this week.</p><TargetForm key={monday} monday={monday} targetBps={target.targetBps} version={target.version} historical={monday<mondayOf(today)}/><Link className="mt-5 block text-sm underline" href={`/admin/food-cost?week=${monday}`}>Default settings, scheduled targets & history</Link></section><section className="card"><h2 className="section-title">Stock planning totals</h2>{week?<OperationForm key={monday} operation="planning" hidden={{weekStart:monday,stamp:week.updatedAt.toISOString(),nextDelivery:week.nextDeliveryDate?.toISOString().slice(0,10)??'',followingDelivery:week.followingDeliveryDate?.toISOString().slice(0,10)??'',...(week.stockAvailabilityConfirmed?{sufficient:'on'}:{})}} fields={[{name:'opening',label:'Opening stock (£)',value:input(week.openingStockPence),hint:'Your manual value is preserved until you change it.'},{name:'expectedClosing',label:'Expected Sunday closing stock (£)',value:input(week.expectedClosingStockPence),hint:'A planning estimate; revise it when needed.'}]} button="Save stock plan"/>:<p>Create the seven-day forecast first.</p>}</section></div>{week&&addDays(monday,6)<=today&&<section className="card mt-5"><h2 className="section-title">Actual Sunday closing stock</h2><p className="mb-4 text-sm text-stone-500">Enter the total stock valuation. Individual product counts are optional.</p><OperationForm operation="closing-total" hidden={{weekStart:monday,stamp:week.updatedAt.toISOString()}} fields={[{name:'amount',label:'Actual closing stock (£)',value:input(week.actualClosingStockPence)},{name:'reason',label:'Reason for historical entry or correction',required:week.actualClosingStockPence!==null||addDays(monday,6)<today}]} button="Save actual closing stock"/></section>}</>}<Link className="mt-6 block text-sm underline" href={`/stock?week=${monday}`}>Optional product catalogue and detailed stock counts</Link></>;
}
