import Link from 'next/link';
import { ChefHat, LogOut, Menu } from 'lucide-react';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { logout } from '@/app/login/actions';
import { WorkspaceSwitcher } from '@/components/workspace-switcher';
import { Navigation } from '@/components/navigation';
export default async function ProtectedLayout({ children }: { children: React.ReactNode }) {
  const user=await requireUser();const restaurant=await db().restaurant.findUniqueOrThrow({where:{id:user.restaurantId}});
  const brand=<Link href="/dashboard" className="flex items-center gap-3 text-white"><span className="brand-mark"><ChefHat size={25} strokeWidth={1.5}/></span><span className="text-xl font-semibold tracking-tight">{restaurant.name}<span className="mt-1 block text-[10px] font-medium uppercase tracking-[.22em] text-[#c6b98c]">Kitchen intelligence</span></span></Link>;
  return <div className="app-shell min-h-dvh lg:grid lg:grid-cols-[236px_minmax(0,1fr)]"><aside className="sidebar hidden lg:sticky lg:top-0 lg:flex lg:h-dvh lg:flex-col"><div className="mb-6">{brand}<WorkspaceSwitcher/></div><p className="mb-4 px-3 text-[10px] font-semibold uppercase tracking-[.22em] text-white/40">Restaurant workspace</p><Navigation admin={user.role==='SUPER_USER'}/><div className="mt-auto rounded-xl border border-white/10 bg-white/5 p-4"><p className="text-sm text-white/90">Your kitchen, in balance.</p><p className="mt-2 text-xs text-white/45">GBP · Excluding VAT<br/>Monday – Sunday · London</p></div></aside><div className="min-w-0"><div className="mobile-brand lg:hidden"><div className="flex items-center justify-between gap-4">{brand}</div><WorkspaceSwitcher/><details className="mobile-menu"><summary className="flex min-h-11 cursor-pointer items-center gap-2 text-sm text-white"><Menu size={20}/>Menu</summary><div className="pt-3"><Navigation admin={user.role==='SUPER_USER'}/></div></details></div><header className="app-header"><p className="text-xs font-medium uppercase tracking-[.15em] text-stone-500">Cocotte Kitchen Intelligence</p><div className="flex items-center gap-4"><div className="text-right"><p className="text-sm font-semibold">{user.name}</p><p className="text-xs text-stone-500">{user.role==='SUPER_USER'?'Super User':'Chef'}</p></div><form action={logout}><button className="icon-button" aria-label="Sign out" title="Sign out"><LogOut size={18}/></button></form></div></header><main className="workspace">{children}</main></div></div>;
}
